//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alunorf_roh_plugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alunorf_roh_plugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .dat file {0} could not be read.
        /// </summary>
        internal static string DatFileCouldNotBeOpened {
            get {
                return ResourceManager.GetString("DatFileCouldNotBeOpened", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon RohTask {
            get {
                object obj = ResourceManager.GetObject("RohTask", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select {
            get {
                object obj = ResourceManager.GetObject("select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select channels for additional Kanalbeschreibung table entries.
        /// </summary>
        internal static string SelectKanal {
            get {
                return ResourceManager.GetString("SelectKanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select infofields for additional Kopfdaten table entries.
        /// </summary>
        internal static string SelectKopf {
            get {
                return ResourceManager.GetString("SelectKopf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select infofields for additional Schlussdaten table entries.
        /// </summary>
        internal static string SelectSchluss {
            get {
                return ResourceManager.GetString("SelectSchluss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select infofields for additional Stichdaten table entries.
        /// </summary>
        internal static string SelectStich {
            get {
                return ResourceManager.GetString("SelectStich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for template .dat file.
        /// </summary>
        internal static string tooltipBrowse {
            get {
                return ResourceManager.GetString("tooltipBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select infofields and channels from .dat file.
        /// </summary>
        internal static string tooltipSelect {
            get {
                return ResourceManager.GetString("tooltipSelect", resourceCulture);
            }
        }
    }
}
