//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alunorf_roh_plugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alunorf_roh_plugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, channel with duplicate name  found in .dat file: &apos;{0}&apos;.
        /// </summary>
        internal static string ChannelalreadyPresent {
            get {
                return ResourceManager.GetString("ChannelalreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die .dat Datei {0} konnte nicht gelesen werden.
        /// </summary>
        internal static string DatFileCouldNotBeOpened {
            get {
                return ResourceManager.GetString("DatFileCouldNotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unerwarteter Fehler beim Lesen der .dat Datei: {0}.
        /// </summary>
        internal static string ErrorDatUnexpected {
            get {
                return ResourceManager.GetString("ErrorDatUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: .roh Datei konnte nicht auf den FTP-Server hochgeladen werden: &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorFtp {
            get {
                return ResourceManager.GetString("ErrorFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: es konnte keine ibaFiles Instanz erstellt werden: {0}.
        /// </summary>
        internal static string ErrorIbaFiles {
            get {
                return ResourceManager.GetString("ErrorIbaFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: .dat Datei konnte nicht geöffnet werden: {0}.
        /// </summary>
        internal static string ErrorIbaFilesOpen {
            get {
                return ResourceManager.GetString("ErrorIbaFilesOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: .roh Datei konnte nicht erzeugt werden: &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorRohFileCreate {
            get {
                return ResourceManager.GetString("ErrorRohFileCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unerwarteter Fehler beim Schreiben der .roh Datei: {0}.
        /// </summary>
        internal static string ErrorRohUnexpected {
            get {
                return ResourceManager.GetString("ErrorRohUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: .roh Datei konnte nicht geschrieben werden: {0}.
        /// </summary>
        internal static string ErrorRohWrite {
            get {
                return ResourceManager.GetString("ErrorRohWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unerwarteter Fehler: {0}.
        /// </summary>
        internal static string ErrorUnexpected {
            get {
                return ResourceManager.GetString("ErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, info field with duplicate name found in .dat file: &apos;{0}&apos;.
        /// </summary>
        internal static string InfoalreadyPresent {
            get {
                return ResourceManager.GetString("InfoalreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: Kanalbeschreibung Tabellenzeile {1}: Daten aus Kanal &apos;{0}&apos; konnten nicht geladen werden..
        /// </summary>
        internal static string KanalDataCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("KanalDataCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: Kanalbeschreibung Tabellenzeile {1}: Kanal &apos;{0}&apos; nicht in der .dat Datei gefunden.
        /// </summary>
        internal static string KanalDataNotFound {
            get {
                return ResourceManager.GetString("KanalDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Kennung&apos; muss ein integer sein.
        /// </summary>
        internal static string KennungNotANumber {
            get {
                return ResourceManager.GetString("KennungNotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: Kopfdaten Tabellenzeile {1}: Infofeld &apos;{0}&apos; nicht in der .dat Datei gefunden.
        /// </summary>
        internal static string KopfDataNotFound {
            get {
                return ResourceManager.GetString("KopfDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon RohTask {
            get {
                object obj = ResourceManager.GetObject("RohTask", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: Schlussdaten Tabellenzeile {1}: Infofeld &apos;{0}&apos; nicht in der .dat Datei gefunden.
        /// </summary>
        internal static string SchlussDataNotFound {
            get {
                return ResourceManager.GetString("SchlussDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap select {
            get {
                object obj = ResourceManager.GetObject("select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahl der Kanäle für weitere Tabelleneinträge der Kanalbeschreibung.
        /// </summary>
        internal static string SelectKanal {
            get {
                return ResourceManager.GetString("SelectKanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahl der Infofelder für weitere Tabelleneinträge der Kopfdaten.
        /// </summary>
        internal static string SelectKopf {
            get {
                return ResourceManager.GetString("SelectKopf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahl der Infofelder für weitere Tabelleneinträge der Schlussdaten.
        /// </summary>
        internal static string SelectSchluss {
            get {
                return ResourceManager.GetString("SelectSchluss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select infofields for additional Stichdaten table entries.
        /// </summary>
        internal static string SelectStich {
            get {
                return ResourceManager.GetString("SelectStich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: Stichdaten Tabellenzeile {1}: Infofeld &apos;{0}&apos; nicht im .dat File gefunden.
        /// </summary>
        internal static string StichDataNotFound {
            get {
                return ResourceManager.GetString("StichDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . roh Datei wurde erfolgreich geschrieben.
        /// </summary>
        internal static string TestSuccess {
            get {
                return ResourceManager.GetString("TestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen nach Formatvorlage .dat Datei.
        /// </summary>
        internal static string tooltipBrowse {
            get {
                return ResourceManager.GetString("tooltipBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahl der Infofelder und Kanäle der .dat Datei.
        /// </summary>
        internal static string tooltipSelect {
            get {
                return ResourceManager.GetString("tooltipSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .roh Test Datei erstellen.
        /// </summary>
        internal static string tooltipTest {
            get {
                return ResourceManager.GetString("tooltipTest", resourceCulture);
            }
        }
    }
}
