//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alunorf_sinec_h1_plugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alunorf_sinec_h1_plugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Aktualisieren {
            get {
                object obj = ResourceManager.GetObject("Aktualisieren", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected.
        /// </summary>
        internal static string connected {
            get {
                return ResourceManager.GetString("connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnected.
        /// </summary>
        internal static string disconnected {
            get {
                return ResourceManager.GetString("disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to one of the first NQS server: .
        /// </summary>
        internal static string err_connect1 {
            get {
                return ResourceManager.GetString("err_connect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to  the second NQS server: .
        /// </summary>
        internal static string err_connect2 {
            get {
                return ResourceManager.GetString("err_connect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to either of the NQS servers: .
        /// </summary>
        internal static string err_connect3 {
            get {
                return ResourceManager.GetString("err_connect3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QDT telegram not (yet) acknowledged.
        /// </summary>
        internal static string err_noAck {
            get {
                return ResourceManager.GetString("err_noAck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the NQS servers is ready to process QDT telegrams.
        /// </summary>
        internal static string err_nogo {
            get {
                return ResourceManager.GetString("err_nogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To many telegrams queued for sending.
        /// </summary>
        internal static string err_queue {
            get {
                return ResourceManager.GetString("err_queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send telegram: .
        /// </summary>
        internal static string err_send {
            get {
                return ResourceManager.GetString("err_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recieving.
        /// </summary>
        internal static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon H1Task {
            get {
                object obj = ResourceManager.GetObject("H1Task", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initialised.
        /// </summary>
        internal static string initialised {
            get {
                return ResourceManager.GetString("initialised", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Speichern {
            get {
                object obj = ResourceManager.GetObject("Speichern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
