//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iba.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iba.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Job.
        /// </summary>
        internal static string addConfigurationText {
            get {
                return ResourceManager.GetString("addConfigurationText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Aktualisieren {
            get {
                object obj = ResourceManager.GetObject("Aktualisieren", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Analyzer_001 {
            get {
                object obj = ResourceManager.GetObject("Analyzer_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes in jobconfiguration to the running job.
        /// </summary>
        internal static string applyStartedButton {
            get {
                return ResourceManager.GetString("applyStartedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script has changed, do you wish to save the scriptfile ?.
        /// </summary>
        internal static string AskToSaveScript {
            get {
                return ResourceManager.GetString("AskToSaveScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nr of attempts exceeded!.
        /// </summary>
        internal static string AttemptsExceeded {
            get {
                return ResourceManager.GetString("AttemptsExceeded", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon batchfile_running {
            get {
                object obj = ResourceManager.GetObject("batchfile_running", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a new script task.
        /// </summary>
        internal static string batchfileButton {
            get {
                return ResourceManager.GetString("batchfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        internal static string batchfileTitle {
            get {
                return ResourceManager.GetString("batchfileTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon brokenfile {
            get {
                object obj = ResourceManager.GetObject("brokenfile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test path.
        /// </summary>
        internal static string checkPathButton {
            get {
                return ResourceManager.GetString("checkPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error cleaning up directories: .
        /// </summary>
        internal static string CleanupDirectoriesFailed {
            get {
                return ResourceManager.GetString("CleanupDirectoriesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing.
        /// </summary>
        internal static string closing {
            get {
                return ResourceManager.GetString("closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string collapseTitle {
            get {
                return ResourceManager.GetString("collapseTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon configuration {
            get {
                object obj = ResourceManager.GetObject("configuration", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon configuration_new {
            get {
                object obj = ResourceManager.GetObject("configuration_new", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon connectedIcon {
            get {
                object obj = ResourceManager.GetObject("connectedIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the ibaDatCoordinator service was lost, ibaDatCoordinator will now continue in offline mode. We recommend you save any changes and restart the service and ibaDatCoordinator..
        /// </summary>
        internal static string connectionLost {
            get {
                return ResourceManager.GetString("connectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Lost.
        /// </summary>
        internal static string connectionLostCaption {
            get {
                return ResourceManager.GetString("connectionLostCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to shared network directory &apos;{0}&apos; : &quot;{1}&quot;.
        /// </summary>
        internal static string ConnectionLostFrom {
            get {
                return ResourceManager.GetString("ConnectionLostFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection restored to shared network directory &apos;{0}&apos;.
        /// </summary>
        internal static string ConnectionRestoredTo {
            get {
                return ResourceManager.GetString("ConnectionRestoredTo", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon copydat_running {
            get {
                object obj = ResourceManager.GetObject("copydat_running", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a new copy task.
        /// </summary>
        internal static string copytaskButton {
            get {
                return ResourceManager.GetString("copytaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string copyTitle {
            get {
                return ResourceManager.GetString("copyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not test validity of the directory.
        /// </summary>
        internal static string CouldNotTestPath {
            get {
                return ResourceManager.GetString("CouldNotTestPath", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string cutTitle {
            get {
                return ResourceManager.GetString("cutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete  the Script options &quot;{0}&quot; of Job &quot;{1}&quot; ?.
        /// </summary>
        internal static string deleteBatchfileQuestion {
            get {
                return ResourceManager.GetString("deleteBatchfileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete Job &quot;{0}&quot; ?.
        /// </summary>
        internal static string deleteConfigurationQuestion {
            get {
                return ResourceManager.GetString("deleteConfigurationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the Copy options &quot;{0}&quot; of Job &quot;{1}&quot; ?.
        /// </summary>
        internal static string deleteCopyTaskQuestion {
            get {
                return ResourceManager.GetString("deleteCopyTaskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the &apos;{0}&apos; options &quot;{1}&quot; of Job &quot;{2}&quot; ?.
        /// </summary>
        internal static string deleteCustomTaskQuestion {
            get {
                return ResourceManager.GetString("deleteCustomTaskQuestion", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap deletedats {
            get {
                object obj = ResourceManager.GetObject("deletedats", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the Extract options &quot;{0}&quot; of Job &quot;{1}&quot; ?.
        /// </summary>
        internal static string deleteExtractQuestion {
            get {
                return ResourceManager.GetString("deleteExtractQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the condition options &quot;{0}&quot; of Job &quot;{1}&quot; ? (dependent tasks will not be deleted).
        /// </summary>
        internal static string deleteIfTaskQuestion {
            get {
                return ResourceManager.GetString("deleteIfTaskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected files.
        /// </summary>
        internal static string deletePermanentErrorFilesButton {
            get {
                return ResourceManager.GetString("deletePermanentErrorFilesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the Report options &quot;{0}&quot; of Job &quot;{1}&quot; ?.
        /// </summary>
        internal static string deleteReportQuestion {
            get {
                return ResourceManager.GetString("deleteReportQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string deleteTitle {
            get {
                return ResourceManager.GetString("deleteTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon disconnectedIcon {
            get {
                object obj = ResourceManager.GetObject("disconnectedIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DOS {
            get {
                object obj = ResourceManager.GetObject("DOS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IbaAnalyzer exceeded the imposed memory limit.
        /// </summary>
        internal static string errAnalyzerMemory {
            get {
                return ResourceManager.GetString("errAnalyzerMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IbaAnalyzer exceeded the imposed time limit.
        /// </summary>
        internal static string errAnalyzerTime {
            get {
                return ResourceManager.GetString("errAnalyzerTime", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon extract_running {
            get {
                object obj = ResourceManager.GetObject("extract_running", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a new extract task.
        /// </summary>
        internal static string extractButton {
            get {
                return ResourceManager.GetString("extractButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        internal static string extractTitle {
            get {
                return ResourceManager.GetString("extractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed! (see logfile).
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Fax {
            get {
                object obj = ResourceManager.GetObject("Fax", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified directory does not exist.
        /// </summary>
        internal static string FolderDoesNotExist {
            get {
                return ResourceManager.GetString("FolderDoesNotExist", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon greenarrow {
            get {
                object obj = ResourceManager.GetObject("greenarrow", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified ibaAnalyzer executable does not exist: .
        /// </summary>
        internal static string IbaAnalyzerExecutableDoesNotExist {
            get {
                return ResourceManager.GetString("IbaAnalyzerExecutableDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IbaAnalyzer critical error, ibaAnalyzer will be restarted.
        /// </summary>
        internal static string IbaAnalyzerUndeterminedError {
            get {
                return ResourceManager.GetString("IbaAnalyzerUndeterminedError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ibalogo_transparent {
            get {
                object obj = ResourceManager.GetObject("ibalogo_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.icsharpcode.net/OpenSource/SD.
        /// </summary>
        internal static string ICSharpTextEditorUrl {
            get {
                return ResourceManager.GetString("ICSharpTextEditorUrl", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon iftask {
            get {
                object obj = ResourceManager.GetObject("iftask", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a new condition task.
        /// </summary>
        internal static string iftaskButton {
            get {
                return ResourceManager.GetString("iftaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string iftaskTitle {
            get {
                return ResourceManager.GetString("iftaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression could not be evaluated, this will be treated as FALSE.
        /// </summary>
        internal static string IfTestBadEvaluation {
            get {
                return ResourceManager.GetString("IfTestBadEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression evaluated to FALSE.
        /// </summary>
        internal static string IfTestNegativeEvaluation {
            get {
                return ResourceManager.GetString("IfTestNegativeEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression evaluated to TRUE.
        /// </summary>
        internal static string IfTestPositiveEvaluation {
            get {
                return ResourceManager.GetString("IfTestPositiveEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .dat file is corrupt are is not a valid iba .dat file.
        /// </summary>
        internal static string InvalidDatFile {
            get {
                return ResourceManager.GetString("InvalidDatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification e-mail address is invalid or not supplied.
        /// </summary>
        internal static string invalidEmail {
            get {
                return ResourceManager.GetString("invalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid path.
        /// </summary>
        internal static string invalidPath {
            get {
                return ResourceManager.GetString("invalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script failed with exitcode: {0}.
        /// </summary>
        internal static string logBatchfileFailed {
            get {
                return ResourceManager.GetString("logBatchfileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script started.
        /// </summary>
        internal static string logBatchfileStarted {
            get {
                return ResourceManager.GetString("logBatchfileStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script successfully completed.
        /// </summary>
        internal static string logBatchfileSuccess {
            get {
                return ResourceManager.GetString("logBatchfileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script timed out.
        /// </summary>
        internal static string logBatchfileTimeout {
            get {
                return ResourceManager.GetString("logBatchfileTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for .dat files.
        /// </summary>
        internal static string logCheckingForNewDatFiles {
            get {
                return ResourceManager.GetString("logCheckingForNewDatFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started processing configuration.
        /// </summary>
        internal static string logConfigurationStarted {
            get {
                return ResourceManager.GetString("logConfigurationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stopped processing configuration.
        /// </summary>
        internal static string logConfigurationStopped {
            get {
                return ResourceManager.GetString("logConfigurationStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to copy file.
        /// </summary>
        internal static string logCopyTaskFailed {
            get {
                return ResourceManager.GetString("logCopyTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file successfully copied.
        /// </summary>
        internal static string logCopyTaskSuccess {
            get {
                return ResourceManager.GetString("logCopyTaskSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to create destination folder.
        /// </summary>
        internal static string logCreateDirectoryFailed {
            get {
                return ResourceManager.GetString("logCreateDirectoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specified .dat folder does not exist.
        /// </summary>
        internal static string logDatDirError {
            get {
                return ResourceManager.GetString("logDatDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extractor failed.
        /// </summary>
        internal static string logExtractFailed {
            get {
                return ResourceManager.GetString("logExtractFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extractor started.
        /// </summary>
        internal static string logExtractStarted {
            get {
                return ResourceManager.GetString("logExtractStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extracting successfully completed.
        /// </summary>
        internal static string logExtractSuccess {
            get {
                return ResourceManager.GetString("logExtractSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extracting timed out.
        /// </summary>
        internal static string logExtractTimeout {
            get {
                return ResourceManager.GetString("logExtractTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this version of ibaDatCoordinator requires ibaAnalyzer version 5.0 or higher.
        /// </summary>
        internal static string logFileVersionToLow {
            get {
                return ResourceManager.GetString("logFileVersionToLow", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon logging {
            get {
                object obj = ResourceManager.GetObject("logging", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to condition evaluated as FALSE.
        /// </summary>
        internal static string logIfTaskEvaluatedFalse {
            get {
                return ResourceManager.GetString("logIfTaskEvaluatedFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to condition evaluated as TRUE.
        /// </summary>
        internal static string logIfTaskEvaluatedTrue {
            get {
                return ResourceManager.GetString("logIfTaskEvaluatedTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started evaluating condition.
        /// </summary>
        internal static string logIfTaskStarted {
            get {
                return ResourceManager.GetString("logIfTaskStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start the job because no license was found for one or more custom tasks.
        /// </summary>
        internal static string logLicenseNoStart {
            get {
                return ResourceManager.GetString("logLicenseNoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped the job because no license was found for one or more custom tasks.
        /// </summary>
        internal static string logLicenseStopped {
            get {
                return ResourceManager.GetString("logLicenseStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to move file.
        /// </summary>
        internal static string logMoveTaskFailed {
            get {
                return ResourceManager.GetString("logMoveTaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file successfully moved.
        /// </summary>
        internal static string logMoveTaskSuccess {
            get {
                return ResourceManager.GetString("logMoveTaskSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file was successfuly moved, subsequent tasks will be ignored.
        /// </summary>
        internal static string logNextTasksIgnored {
            get {
                return ResourceManager.GetString("logNextTasksIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scriptfile does not exist.
        /// </summary>
        internal static string logNoBatchfile {
            get {
                return ResourceManager.GetString("logNoBatchfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pdo file for extractor does not exist.
        /// </summary>
        internal static string logNoExtractPdo {
            get {
                return ResourceManager.GetString("logNoExtractPdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No destination directory specified for the task..
        /// </summary>
        internal static string logNoOutputPathSpecified {
            get {
                return ResourceManager.GetString("logNoOutputPathSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pdo file for report generator does not exist.
        /// </summary>
        internal static string logNoReportPdo {
            get {
                return ResourceManager.GetString("logNoReportPdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a specified parameter is invalid.
        /// </summary>
        internal static string logNotifcationInvalidParameter {
            get {
                return ResourceManager.GetString("logNotifcationInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user does not have access to the requested information.
        /// </summary>
        internal static string logNotificationAccessDenied {
            get {
                return ResourceManager.GetString("logNotificationAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notification failed.
        /// </summary>
        internal static string logNotificationFailed {
            get {
                return ResourceManager.GetString("logNotificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the user name could not be found.
        /// </summary>
        internal static string logNotificationNameNotFound {
            get {
                return ResourceManager.GetString("logNotificationNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a general failure occurred in the network hardware .
        /// </summary>
        internal static string logNotificationNetworkError {
            get {
                return ResourceManager.GetString("logNotificationNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this network request is not supported.
        /// </summary>
        internal static string logNotificationNotSupported {
            get {
                return ResourceManager.GetString("logNotificationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks destination directory is the same as .dat file directory of its parent job..
        /// </summary>
        internal static string logOutputIsInput {
            get {
                return ResourceManager.GetString("logOutputIsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading assembly {0} : &apos;{1}&apos;.
        /// </summary>
        internal static string logPluginLoadError {
            get {
                return ResourceManager.GetString("logPluginLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to remove old folder.
        /// </summary>
        internal static string logRemoveDirectoryFailed {
            get {
                return ResourceManager.GetString("logRemoveDirectoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report generator failed.
        /// </summary>
        internal static string logReportFailed {
            get {
                return ResourceManager.GetString("logReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report generator started.
        /// </summary>
        internal static string logReportStarted {
            get {
                return ResourceManager.GetString("logReportStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report successfully completed.
        /// </summary>
        internal static string logReportSuccess {
            get {
                return ResourceManager.GetString("logReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reporting timed out.
        /// </summary>
        internal static string logReportTimeout {
            get {
                return ResourceManager.GetString("logReportTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibaDatCoordinator service started.
        /// </summary>
        internal static string logServiceStarted {
            get {
                return ResourceManager.GetString("logServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibaDatCoordinator service stopped.
        /// </summary>
        internal static string logServiceStopped {
            get {
                return ResourceManager.GetString("logServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No license found for custom task &apos;{0}&apos;.
        /// </summary>
        internal static string logTaskNotLicensed {
            get {
                return ResourceManager.GetString("logTaskNotLicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; task succesfully completed .
        /// </summary>
        internal static string logTaskSuccess {
            get {
                return ResourceManager.GetString("logTaskSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string logTitle {
            get {
                return ResourceManager.GetString("logTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon memoryexceeded {
            get {
                object obj = ResourceManager.GetObject("memoryexceeded", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to memory limit exceeded!.
        /// </summary>
        internal static string MemoryExceededTaskText {
            get {
                return ResourceManager.GetString("MemoryExceededTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Script Task.
        /// </summary>
        internal static string NewBatchfileTitle {
            get {
                return ResourceManager.GetString("NewBatchfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Job.
        /// </summary>
        internal static string newConfigurationName {
            get {
                return ResourceManager.GetString("newConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Copy Task.
        /// </summary>
        internal static string NewCopyTaskTitle {
            get {
                return ResourceManager.GetString("NewCopyTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &apos;{0}&apos; Task.
        /// </summary>
        internal static string NewCustomTaskTitle {
            get {
                return ResourceManager.GetString("NewCustomTaskTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NewDocument {
            get {
                object obj = ResourceManager.GetObject("NewDocument", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Extract Task.
        /// </summary>
        internal static string NewExtractTitle {
            get {
                return ResourceManager.GetString("NewExtractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Condition.
        /// </summary>
        internal static string NewIfTaskTitle {
            get {
                return ResourceManager.GetString("NewIfTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Report Task.
        /// </summary>
        internal static string NewReportTitle {
            get {
                return ResourceManager.GetString("NewReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        internal static string NewTaskTitle {
            get {
                return ResourceManager.GetString("NewTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibaDatCoordinator (connected).
        /// </summary>
        internal static string niConnected {
            get {
                return ResourceManager.GetString("niConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibaDatCoordinator (disconnected).
        /// </summary>
        internal static string niDisconnected {
            get {
                return ResourceManager.GetString("niDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibaDatCoordinator (running).
        /// </summary>
        internal static string niRunning {
            get {
                return ResourceManager.GetString("niRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to momentarely no access to .dat  file....
        /// </summary>
        internal static string Noaccess {
            get {
                return ResourceManager.GetString("Noaccess", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon noaccess1 {
            get {
                object obj = ResourceManager.GetObject("noaccess1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dat  file is readonly.
        /// </summary>
        internal static string Noaccess2 {
            get {
                return ResourceManager.GetString("Noaccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDA not yet finished with .dat file.
        /// </summary>
        internal static string Noaccess3 {
            get {
                return ResourceManager.GetString("Noaccess3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no ibaAnalyzer registered.
        /// </summary>
        internal static string noIbaAnalyser {
            get {
                return ResourceManager.GetString("noIbaAnalyser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous task did not generate a file to use in the script arguments.
        /// </summary>
        internal static string NoPreviousOutPutFile {
            get {
                return ResourceManager.GetString("NoPreviousOutPutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous task did not generate a file to copy.
        /// </summary>
        internal static string NoPreviousOutPutFileToCopy {
            get {
                return ResourceManager.GetString("NoPreviousOutPutFileToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibaDatCoordinator notification.
        /// </summary>
        internal static string NotificationEmailSubject {
            get {
                return ResourceManager.GetString("NotificationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &quot;{0}&quot; for job &quot;{1}&quot; failed for the following .dat files :.
        /// </summary>
        internal static string NotificationFailures {
            get {
                return ResourceManager.GetString("NotificationFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task &quot;{0}&quot; for job &quot;{1}&quot; was completed successfully for the following .dat files :.
        /// </summary>
        internal static string NotificationSuccesses {
            get {
                return ResourceManager.GetString("NotificationSuccesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string notifyIconMenuItemExit {
            get {
                return ResourceManager.GetString("notifyIconMenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string notifyIconMenuItemRestore {
            get {
                return ResourceManager.GetString("notifyIconMenuItemRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Service.
        /// </summary>
        internal static string notifyIconMenuItemStartService {
            get {
                return ResourceManager.GetString("notifyIconMenuItemStartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Service.
        /// </summary>
        internal static string notifyIconMenuItemStopService {
            get {
                return ResourceManager.GetString("notifyIconMenuItemStopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibaDatCoordinator notifications test message.
        /// </summary>
        internal static string notifyTestMessage {
            get {
                return ResourceManager.GetString("notifyTestMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem opening file:.
        /// </summary>
        internal static string OpenFileProblem {
            get {
                return ResourceManager.GetString("OpenFileProblem", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string pasteTitle {
            get {
                return ResourceManager.GetString("pasteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permanently failed .dat files.
        /// </summary>
        internal static string PermanentlyFailedDatFiles {
            get {
                return ResourceManager.GetString("PermanentlyFailedDatFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority of application:.
        /// </summary>
        internal static string PriorityApp {
            get {
                return ResourceManager.GetString("PriorityApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read status of the dat-file.
        /// </summary>
        internal static string ReadStatusError {
            get {
                return ResourceManager.GetString("ReadStatusError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon redarrow {
            get {
                object obj = ResourceManager.GetObject("redarrow", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon redarrow1 {
            get {
                object obj = ResourceManager.GetObject("redarrow1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refreshconfs {
            get {
                object obj = ResourceManager.GetObject("refreshconfs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the &quot;allready processed&quot; mark from the dat files.
        /// </summary>
        internal static string refreshDatButton {
            get {
                return ResourceManager.GetString("refreshDatButton", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap refreshdats {
            get {
                object obj = ResourceManager.GetObject("refreshdats", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove markings from selected files so they will be reprocessed..
        /// </summary>
        internal static string refreshPermanentErrorFilesButton {
            get {
                return ResourceManager.GetString("refreshPermanentErrorFilesButton", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon report_running {
            get {
                object obj = ResourceManager.GetObject("report_running", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a new report task.
        /// </summary>
        internal static string reportButton {
            get {
                return ResourceManager.GetString("reportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string reportTitle {
            get {
                return ResourceManager.GetString("reportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to running....
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon runningIcon {
            get {
                object obj = ResourceManager.GetObject("runningIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem saving file:.
        /// </summary>
        internal static string SaveFileProblem {
            get {
                return ResourceManager.GetString("SaveFileProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current jobs ?.
        /// </summary>
        internal static string saveQuestion {
            get {
                return ResourceManager.GetString("saveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments for the script could not be parsed.
        /// </summary>
        internal static string ScriptArgumentsCouldNotBeParsed {
            get {
                return ResourceManager.GetString("ScriptArgumentsCouldNotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scriptfile does not exist.
        /// </summary>
        internal static string ScriptNoExist {
            get {
                return ResourceManager.GetString("ScriptNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scriptfile is readonly.
        /// </summary>
        internal static string ScriptReadOnly {
            get {
                return ResourceManager.GetString("ScriptReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem saving file at server side.
        /// </summary>
        internal static string ServerSaveFileProblem {
            get {
                return ResourceManager.GetString("ServerSaveFileProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem connecting to the ibaDatCoordinator service : &apos;&apos;{0}&quot;{1}ibaDatCoordinator will continue in disconnected mode..
        /// </summary>
        internal static string ServiceConnectProblem {
            get {
                return ResourceManager.GetString("ServiceConnectProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service could not be started.
        /// </summary>
        internal static string ServiceConnectProblem2 {
            get {
                return ResourceManager.GetString("ServiceConnectProblem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem connecting to the ibaDatCoordinator service :&quot;{0}&quot;{1}Please stop the service manually.
        /// </summary>
        internal static string ServiceConnectProblem3 {
            get {
                return ResourceManager.GetString("ServiceConnectProblem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service could not be stopped.
        /// </summary>
        internal static string ServiceConnectProblem4 {
            get {
                return ResourceManager.GetString("ServiceConnectProblem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the ibaDatCoordinator Service.
        /// </summary>
        internal static string ServiceConnectProblemCaption {
            get {
                return ResourceManager.GetString("ServiceConnectProblemCaption", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsTitle {
            get {
                return ResourceManager.GetString("settingsTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Speichern {
            get {
                object obj = ResourceManager.GetObject("Speichern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon standalone {
            get {
                object obj = ResourceManager.GetObject("standalone", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start {
            get {
                object obj = ResourceManager.GetObject("Start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start this job.
        /// </summary>
        internal static string startButton {
            get {
                return ResourceManager.GetString("startButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the statusdata for Job : {0}.
        /// </summary>
        internal static string statText0 {
            get {
                return ResourceManager.GetString("statText0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job is {0}.
        /// </summary>
        internal static string statText1 {
            get {
                return ResourceManager.GetString("statText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started.
        /// </summary>
        internal static string statText2 {
            get {
                return ResourceManager.GetString("statText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stopped.
        /// </summary>
        internal static string statText3 {
            get {
                return ResourceManager.GetString("statText3", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon status {
            get {
                object obj = ResourceManager.GetObject("status", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! &quot;{0}&quot; Please examine log .
        /// </summary>
        internal static string StatusBarError {
            get {
                return ResourceManager.GetString("StatusBarError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping All Jobs .
        /// </summary>
        internal static string stopAllConfigurations {
            get {
                return ResourceManager.GetString("stopAllConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop this job.
        /// </summary>
        internal static string stopButton {
            get {
                return ResourceManager.GetString("stopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Job.
        /// </summary>
        internal static string stopConfiguration {
            get {
                return ResourceManager.GetString("stopConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully completed.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon success1 {
            get {
                object obj = ResourceManager.GetObject("success1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a test message.
        /// </summary>
        internal static string testNotifications {
            get {
                return ResourceManager.GetString("testNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string textFileStopped {
            get {
                return ResourceManager.GetString("textFileStopped", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap thumbdown {
            get {
                object obj = ResourceManager.GetObject("thumbdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap thumup {
            get {
                object obj = ResourceManager.GetObject("thumup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timed out! (see logfile).
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon timeout1 {
            get {
                object obj = ResourceManager.GetObject("timeout1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon tomanytimestried {
            get {
                object obj = ResourceManager.GetObject("tomanytimestried", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically run this job on service start or file loading.
        /// </summary>
        internal static string toolTipAutoStart {
            get {
                return ResourceManager.GetString("toolTipAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for test file.
        /// </summary>
        internal static string tooltipBrowseTestFile {
            get {
                return ResourceManager.GetString("tooltipBrowseTestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test script.
        /// </summary>
        internal static string tooltipExecuteScript {
            get {
                return ResourceManager.GetString("tooltipExecuteScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New script.
        /// </summary>
        internal static string tooltipNewScript {
            get {
                return ResourceManager.GetString("tooltipNewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open script from file.
        /// </summary>
        internal static string tooltipOpenScript {
            get {
                return ResourceManager.GetString("tooltipOpenScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save script to file.
        /// </summary>
        internal static string tooltipSaveScript {
            get {
                return ResourceManager.GetString("tooltipSaveScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ALLjobs.
        /// </summary>
        internal static string toolTipStartAll {
            get {
                return ResourceManager.GetString("toolTipStartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop ALL jobs.
        /// </summary>
        internal static string toolTipStopAll {
            get {
                return ResourceManager.GetString("toolTipStopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .dat file could not be processed within the maximum number of attempts, further processing will not be attempted.
        /// </summary>
        internal static string TriedToManyTimes {
            get {
                return ResourceManager.GetString("TriedToManyTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the UNC path &apos;{0}&apos;.
        /// </summary>
        internal static string UNCPathUnavailable {
            get {
                return ResourceManager.GetString("UNCPathUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the jobconfiguration was updated.
        /// </summary>
        internal static string UpdateHappened {
            get {
                return ResourceManager.GetString("UpdateHappened", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon watchdog {
            get {
                object obj = ResourceManager.GetObject("watchdog", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP/IP Watchdog.
        /// </summary>
        internal static string watchdogTitle {
            get {
                return ResourceManager.GetString("watchdogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP/IP watchdog : socket exception on accept : {0}.
        /// </summary>
        internal static string wdErrorAccept {
            get {
                return ResourceManager.GetString("wdErrorAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while connecting in TCP/IP watchdog : {0}.
        /// </summary>
        internal static string wdErrorConnect {
            get {
                return ResourceManager.GetString("wdErrorConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending TCP/IP watchdog : {0} --&gt; Disconnecting.
        /// </summary>
        internal static string wdErrorSend {
            get {
                return ResourceManager.GetString("wdErrorSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when stopping TCP/IP watchdog : {0}.
        /// </summary>
        internal static string wdErrorStop {
            get {
                return ResourceManager.GetString("wdErrorStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        internal static string wdTcpIpConnected {
            get {
                return ResourceManager.GetString("wdTcpIpConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening....
        /// </summary>
        internal static string wdTcpIpListening {
            get {
                return ResourceManager.GetString("wdTcpIpListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string wdTcpIpNotConnected {
            get {
                return ResourceManager.GetString("wdTcpIpNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to execute after succes.
        /// </summary>
        internal static string WhenToDo1 {
            get {
                return ResourceManager.GetString("WhenToDo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to execute after failure.
        /// </summary>
        internal static string WhenToDo2 {
            get {
                return ResourceManager.GetString("WhenToDo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to always execute.
        /// </summary>
        internal static string WhenToDo3 {
            get {
                return ResourceManager.GetString("WhenToDo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to execute after 1st failure.
        /// </summary>
        internal static string WhenToDo4 {
            get {
                return ResourceManager.GetString("WhenToDo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frequency.
        /// </summary>
        internal static string XFrequency {
            get {
                return ResourceManager.GetString("XFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/length.
        /// </summary>
        internal static string XInvLength {
            get {
                return ResourceManager.GetString("XInvLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length.
        /// </summary>
        internal static string XLength {
            get {
                return ResourceManager.GetString("XLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        internal static string XTime {
            get {
                return ResourceManager.GetString("XTime", resourceCulture);
            }
        }
    }
}
