!define EUP_INDEX_PDA 0
!define EUP_INDEX_CAM 1
!define EUP_INDEX_LOGIC 2
!define EUP_INDEX_HD 3
!define EUP_INDEX_ROTATE 4
!define EUP_INDEX_VISION 5
!define EUP_INDEX_DAVIS 6
!define EUP_INDEX_7 7
!define EUP_INDEX_8 8
!define EUP_INDEX_9 9