<?xml version="1.0" encoding="utf-8"?>
<IOConfiguration version="2">
  <General>
    <SlowTimebase>100000</SlowTimebase>
    <PCIInterruptBusNr>0</PCIInterruptBusNr>
    <PCIInterruptSlotNr>0</PCIInterruptSlotNr>
    <EnglishS7Operands>1</EnglishS7Operands>
    <AutoStartOnStartup>0</AutoStartOnStartup>
    <AutoRestartOnError>0</AutoRestartOnError>
    <FobFastBrokenLinkDetection>0</FobFastBrokenLinkDetection>
    <AutoDisableModulesOnBrokenFobFastLink>0</AutoDisableModulesOnBrokenFobFastLink>
    <DisableOPCItemWarnings>1</DisableOPCItemWarnings>
    <HPCiTOCSettings>
      <AddressbookPath>C:\HPCi\AddressBooks</AddressbookPath>
      <AddressbookUserName>
      </AddressbookUserName>
      <AddressbookPassword>
      </AddressbookPassword>
      <SyncTime>0</SyncTime>
    </HPCiTOCSettings>
    <DCF77>
      <Active_0>0</Active_0>
      <Signal_0>[0:65535.16383]</Signal_0>
      <Polarity_0>0</Polarity_0>
      <Active_1>0</Active_1>
      <Signal_1>[0:65535.16383]</Signal_1>
      <Polarity_1>0</Polarity_1>
      <SyncOnSeconds>0</SyncOnSeconds>
    </DCF77>
  </General>
  <PcInterfaces>
    <PcInterface id="0x28000000">
      <Name>OPC</Name>
      <AllowInaccessibleServers>0</AllowInaccessibleServers>
      <Links>
        <Link id="0x28000000" />
      </Links>
    </PcInterface>
    <PcInterface id="0x0C000000">
      <Name>TCP/IP Modbus</Name>
      <ModbusResponse>0</ModbusResponse>
      <ModbusDigSwapping>0</ModbusDigSwapping>
      <ModbusByteSwapping>1</ModbusByteSwapping>
      <Links>
        <Link id="0x0C000000" />
      </Links>
    </PcInterface>
    <PcInterface id="0x10000000">
      <Name>TCP/IP VIP</Name>
      <Links>
        <Link id="0x10000000" />
      </Links>
    </PcInterface>
    <PcInterface id="0x2C000000">
      <Name>Virtual</Name>
      <Links>
        <Link id="0x2C000000" />
      </Links>
    </PcInterface>
  </PcInterfaces>
  <Modules>
    <Module>
      <Name>VIP Real</Name>
      <ModuleType>10</ModuleType>
      <Timebase>100000</Timebase>
      <Enabled>1</Enabled>
      <Locked>0</Locked>
      <UseGlobalTimebase>1</UseGlobalTimebase>
      <ModuleNr>0</ModuleNr>
      <Valid>1</Valid>
      <SwapMode>0</SwapMode>
      <AsyncMode>0</AsyncMode>
      <NrAnalogSignals>32</NrAnalogSignals>
      <Links>
        <Link Name="">
          <Region>9</Region>
          <InterfaceLink>0x10000000</InterfaceLink>
          <Analog>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4096</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>testsignal</Name>
              <DataType>2</DataType>
              <Offset>4100</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>testsignal2</Name>
              <DataType>2</DataType>
              <Offset>4104</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4108</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4112</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4116</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4120</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4124</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4128</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4132</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4136</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4140</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4144</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4148</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4152</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4156</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4160</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4164</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4168</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4172</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4176</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4180</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4184</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4188</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4192</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4196</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4200</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4204</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4208</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4212</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4216</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4220</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
          </Analog>
          <Digital>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>2</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>4</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>8</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>16</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>32</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>64</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>128</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>256</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>512</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1024</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>2048</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>4096</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>8192</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>16384</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>32768</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>65536</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>131072</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>262144</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>524288</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1048576</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>2097152</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>4194304</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>8388608</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>16777216</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>33554432</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>67108864</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>134217728</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>268435456</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>536870912</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1073741824</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2048</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>-2147483648</Mask>
              <Active>1</Active>
            </Signal>
          </Digital>
        </Link>
      </Links>
    </Module>
    <Module>
      <Name>VIP Real</Name>
      <ModuleType>10</ModuleType>
      <Timebase>100000</Timebase>
      <Enabled>1</Enabled>
      <Locked>0</Locked>
      <UseGlobalTimebase>1</UseGlobalTimebase>
      <ModuleNr>1</ModuleNr>
      <Valid>1</Valid>
      <SwapMode>0</SwapMode>
      <AsyncMode>0</AsyncMode>
      <NrAnalogSignals>32</NrAnalogSignals>
      <Links>
        <Link Name="">
          <Region>9</Region>
          <InterfaceLink>0x10010000</InterfaceLink>
          <Analog>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4224</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4228</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4232</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4236</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4240</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4244</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4248</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4252</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4256</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4260</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4264</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4268</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4272</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4276</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4280</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4284</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4288</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4292</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4296</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4300</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4304</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4308</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4312</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4316</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4320</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4324</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4328</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4332</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4336</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4340</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4344</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>2</DataType>
              <Offset>4348</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
            </Signal>
          </Analog>
          <Digital>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>2</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>4</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>8</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>16</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>32</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>64</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>128</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>256</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>512</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1024</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>2048</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>4096</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>8192</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>16384</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>32768</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>65536</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>131072</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>262144</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>524288</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1048576</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>2097152</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>4194304</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>8388608</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>16777216</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>33554432</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>67108864</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>134217728</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>268435456</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>536870912</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1073741824</Mask>
              <Active>1</Active>
            </Signal>
            <Signal>
              <Name>
              </Name>
              <DataType>0</DataType>
              <Offset>2052</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>-2147483648</Mask>
              <Active>1</Active>
            </Signal>
          </Digital>
        </Link>
      </Links>
    </Module>
    <Module>
      <Name>Virtual</Name>
      <ModuleType>5</ModuleType>
      <Timebase>100000</Timebase>
      <Enabled>1</Enabled>
      <Locked>0</Locked>
      <UseGlobalTimebase>1</UseGlobalTimebase>
      <ModuleNr>9000</ModuleNr>
      <Valid>1</Valid>
      <SwapMode>0</SwapMode>
      <AsyncMode>0</AsyncMode>
      <Links>
        <Link Name="">
          <Region>0</Region>
          <InterfaceLink>0x2C000000</InterfaceLink>
          <Analog>
            <Signal>
              <Name>name_chan0</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>0</Expression>
            </Signal>
            <Signal>
              <Name>name_chan1</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>1</Expression>
            </Signal>
            <Signal>
              <Name>name_chan2</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>2</Expression>
            </Signal>
            <Signal>
              <Name>name_chan3</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>3</Expression>
            </Signal>
            <Signal>
              <Name>name_chan4</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>4</Expression>
            </Signal>
            <Signal>
              <Name>name_chan5</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>5</Expression>
            </Signal>
            <Signal>
              <Name>name_chan6</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>6</Expression>
            </Signal>
            <Signal>
              <Name>name_chan7</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>7</Expression>
            </Signal>
            <Signal>
              <Name>name_chan8</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>8</Expression>
            </Signal>
            <Signal>
              <Name>name_chan9</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>9</Expression>
            </Signal>
            <Signal>
              <Name>name_chan10</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>10</Expression>
            </Signal>
            <Signal>
              <Name>name_chan11</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>11</Expression>
            </Signal>
            <Signal>
              <Name>name_chan12</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>12</Expression>
            </Signal>
            <Signal>
              <Name>name_chan13</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>13</Expression>
            </Signal>
            <Signal>
              <Name>name_chan14</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>14</Expression>
            </Signal>
            <Signal>
              <Name>name_chan15</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>15</Expression>
            </Signal>
            <Signal>
              <Name>name_chan16</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>16</Expression>
            </Signal>
            <Signal>
              <Name>name_chan17</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>17</Expression>
            </Signal>
            <Signal>
              <Name>name_chan18</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>18</Expression>
            </Signal>
            <Signal>
              <Name>name_chan19</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>19</Expression>
            </Signal>
            <Signal>
              <Name>name_chan20</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>20</Expression>
            </Signal>
            <Signal>
              <Name>name_chan21</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>21</Expression>
            </Signal>
            <Signal>
              <Name>name_chan22</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>22</Expression>
            </Signal>
            <Signal>
              <Name>name_chan23</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>23</Expression>
            </Signal>
            <Signal>
              <Name>name_chan24</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>24</Expression>
            </Signal>
            <Signal>
              <Name>name_chan25</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>25</Expression>
            </Signal>
            <Signal>
              <Name>name_chan26</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>26</Expression>
            </Signal>
            <Signal>
              <Name>name_chan27</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>27</Expression>
            </Signal>
            <Signal>
              <Name>name_chan28</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>28</Expression>
            </Signal>
            <Signal>
              <Name>name_chan29</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>29</Expression>
            </Signal>
            <Signal>
              <Name>name_chan30</Name>
              <DataType>2</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Unit>
              </Unit>
              <Active>1</Active>
              <ScaleOffset>0</ScaleOffset>
              <ScaleGain>1</ScaleGain>
              <X1>32767</X1>
              <X2>-32768</X2>
              <Expression>30</Expression>
            </Signal>
          </Analog>
          <Digital>
            <Signal>
              <Name>1</Name>
              <DataType>0</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1</Mask>
              <Active>0</Active>
              <Expression>1</Expression>
            </Signal>
            <Signal>
              <Name>2</Name>
              <DataType>0</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1</Mask>
              <Active>0</Active>
              <Expression>2</Expression>
            </Signal>
            <Signal>
              <Name>5</Name>
              <DataType>0</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1</Mask>
              <Active>0</Active>
              <Expression>5</Expression>
            </Signal>
            <Signal>
              <Name>5</Name>
              <DataType>0</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1</Mask>
              <Active>0</Active>
              <Expression>5</Expression>
            </Signal>
            <Signal>
              <Name>5</Name>
              <DataType>0</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1</Mask>
              <Active>0</Active>
              <Expression>5</Expression>
            </Signal>
            <Signal>
              <Name>5</Name>
              <DataType>0</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1</Mask>
              <Active>0</Active>
              <Expression>5</Expression>
            </Signal>
            <Signal>
              <Name>5</Name>
              <DataType>0</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1</Mask>
              <Active>0</Active>
              <Expression>5</Expression>
            </Signal>
            <Signal>
              <Name>5</Name>
              <DataType>0</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1</Mask>
              <Active>0</Active>
              <Expression>5</Expression>
            </Signal>
            <Signal>
              <Name>5</Name>
              <DataType>0</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1</Mask>
              <Active>0</Active>
              <Expression>5</Expression>
            </Signal>
            <Signal>
              <Name>5</Name>
              <DataType>0</DataType>
              <Offset>0</Offset>
              <Comment1>
              </Comment1>
              <Comment2>
              </Comment2>
              <Mask>1</Mask>
              <Active>0</Active>
              <Expression>5</Expression>
            </Signal>
          </Digital>
        </Link>
      </Links>
    </Module>
  </Modules>
  <Groups />
  <GlobalTechnostringConfiguration>
    <Technostrings>
      <Technostring Name="Technostring 1" Type="1">
        <InterfaceConfig>
          <Terminator>13</Terminator>
          <CharacterSpacing>0</CharacterSpacing>
          <PortNr>2001</PortNr>
          <Baudrate>9600</Baudrate>
          <DataBits>8</DataBits>
          <StopBits>0</StopBits>
          <Parity>0</Parity>
          <FileName>c:\dat\techno.txt</FileName>
          <DataOffset>4096</DataOffset>
          <CounterOffset>8192</CounterOffset>
          <OPC.ComputerName>DEVPC-MICHAEL</OPC.ComputerName>
          <OPC.OPCServerId>
          </OPC.OPCServerId>
          <OPC.OPCItemTag>
          </OPC.OPCItemTag>
          <OPC.UserName>
          </OPC.UserName>
          <OPC.DomainName>
          </OPC.DomainName>
          <OPC.Password>
          </OPC.Password>
          <DataLength>100</DataLength>
          <BoardIndex>0</BoardIndex>
          <SwapMode>0</SwapMode>
          <CustomTechnoSettings />
        </InterfaceConfig>
        <Sections>
          <Section>
            <Name>numeric field</Name>
            <StartIndex>0</StartIndex>
            <StopIndex>5</StopIndex>
          </Section>
        </Sections>
      </Technostring>
      <Technostring Name="Technostring 2" Type="9">
        <InterfaceConfig>
          <Terminator>13</Terminator>
          <CharacterSpacing>0</CharacterSpacing>
          <PortNr>0</PortNr>
          <Baudrate>9600</Baudrate>
          <DataBits>8</DataBits>
          <StopBits>0</StopBits>
          <Parity>0</Parity>
          <FileName>c:\dat\techno.txt</FileName>
          <DataOffset>4096</DataOffset>
          <CounterOffset>8192</CounterOffset>
          <OPC.ComputerName>DEVPC-MICHAEL</OPC.ComputerName>
          <OPC.OPCServerId>
          </OPC.OPCServerId>
          <OPC.OPCItemTag>
          </OPC.OPCItemTag>
          <OPC.UserName>
          </OPC.UserName>
          <OPC.DomainName>
          </OPC.DomainName>
          <OPC.Password>
          </OPC.Password>
          <DataLength>100</DataLength>
          <BoardIndex>0</BoardIndex>
          <SwapMode>0</SwapMode>
          <CustomTechnoSettings>
            <Field>
              <Type>0</Type>
              <Signal>[0:0]</Signal>
              <TechnoSection>
              </TechnoSection>
              <Text>MNR456789012</Text>
              <Format.NrDigits>1</Format.NrDigits>
              <Format.NrDecimals>2</Format.NrDecimals>
              <Length>12</Length>
            </Field>
            <Field>
              <Type>0</Type>
              <Signal>[0:0]</Signal>
              <TechnoSection>
              </TechnoSection>
              <Text>FILL</Text>
              <Format.NrDigits>1</Format.NrDigits>
              <Format.NrDecimals>2</Format.NrDecimals>
              <Length>4</Length>
            </Field>
            <Field>
              <Type>0</Type>
              <Signal>[0:0]</Signal>
              <TechnoSection>
              </TechnoSection>
              <Text>MNRAS6789012</Text>
              <Format.NrDigits>1</Format.NrDigits>
              <Format.NrDecimals>2</Format.NrDecimals>
              <Length>12</Length>
            </Field>
            <Field>
              <Type>0</Type>
              <Signal>[0:0]</Signal>
              <TechnoSection>
              </TechnoSection>
              <Text>MNRBS6789012</Text>
              <Format.NrDigits>1</Format.NrDigits>
              <Format.NrDecimals>2</Format.NrDecimals>
              <Length>12</Length>
            </Field>
            <Field>
              <Type>0</Type>
              <Signal>[0:0]</Signal>
              <TechnoSection>
              </TechnoSection>
              <Text>1</Text>
              <Format.NrDigits>1</Format.NrDigits>
              <Format.NrDecimals>2</Format.NrDecimals>
              <Length>1</Length>
            </Field>
            <Field>
              <Type>0</Type>
              <Signal>[0:0]</Signal>
              <TechnoSection>
              </TechnoSection>
              <Text>2</Text>
              <Format.NrDigits>1</Format.NrDigits>
              <Format.NrDecimals>2</Format.NrDecimals>
              <Length>1</Length>
            </Field>
            <Field>
              <Type>0</Type>
              <Signal>[0:0]</Signal>
              <TechnoSection>
              </TechnoSection>
              <Text>3</Text>
              <Format.NrDigits>1</Format.NrDigits>
              <Format.NrDecimals>2</Format.NrDecimals>
              <Length>1</Length>
            </Field>
            <Field>
              <Type>0</Type>
              <Signal>[0:0]</Signal>
              <TechnoSection>
              </TechnoSection>
              <Text>AVO_</Text>
              <Format.NrDigits>1</Format.NrDigits>
              <Format.NrDecimals>2</Format.NrDecimals>
              <Length>4</Length>
            </Field>
          </CustomTechnoSettings>
        </InterfaceConfig>
        <Sections>
          <Section>
            <Name>MNR</Name>
            <StartIndex>0</StartIndex>
            <StopIndex>11</StopIndex>
          </Section>
          <Section>
            <Name>FILLER</Name>
            <StartIndex>12</StartIndex>
            <StopIndex>15</StopIndex>
          </Section>
          <Section>
            <Name>MNRAS</Name>
            <StartIndex>16</StartIndex>
            <StopIndex>27</StopIndex>
          </Section>
          <Section>
            <Name>MNRBS</Name>
            <StartIndex>28</StartIndex>
            <StopIndex>39</StopIndex>
          </Section>
          <Section>
            <Name>FA_KD_POS</Name>
            <StartIndex>40</StartIndex>
            <StopIndex>40</StopIndex>
          </Section>
          <Section>
            <Name>FERTIGUNGS_POS</Name>
            <StartIndex>41</StartIndex>
            <StopIndex>41</StopIndex>
          </Section>
          <Section>
            <Name>LFD_NR_ALTERN_AVO</Name>
            <StartIndex>42</StartIndex>
            <StopIndex>42</StopIndex>
          </Section>
          <Section>
            <Name>AVO_NR</Name>
            <StartIndex>43</StartIndex>
            <StopIndex>46</StopIndex>
          </Section>
        </Sections>
      </Technostring>
    </Technostrings>
  </GlobalTechnostringConfiguration>
</IOConfiguration>