// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.6.0.0
//    <NameSpace>XmlExtract</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><PascalCase>False</PascalCase><BaseClassName>EntityBase</BaseClassName><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>True</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings>System.Xml</CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><InitializeFields>All</InitializeFields><GenerateAllTypes>True</GenerateAllTypes>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace XmlExtract
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.thyssen.com/xml/schema/qbic")]
    [System.Xml.Serialization.XmlRootAttribute("Erzeugung", Namespace="http://www.thyssen.com/xml/schema/qbic", IsNullable=false)]
    public partial class MaterialEreignisType
    {
        
        public MaterialHeaderType MaterialHeader { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("Messung")]
        public List<MessungType> Messung { get; set; }
        
        /// <summary>
        /// MaterialEreignisType class constructor
        /// </summary>
        public MaterialEreignisType()
        {
            this.Messung = new List<MessungType>();
            this.MaterialHeader = new MaterialHeaderType();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.thyssen.com/xml/schema/qbic")]
    public partial class MaterialHeaderType
    {
        
        private System.Nullable<StandortType> standortField;
        
        private System.Nullable<MaterialArtType> materialArtField;
        
        public string LokalerIdent { get; set; }
        
        /// <summary>
        /// BO, DO, DU
        /// </summary>
        public StandortType Standort
        {
            get
            {
                if (this.standortField.HasValue)
                {
                    return this.standortField.Value;
                }
                else
                {
                    return default(StandortType);
                }
            }
            set
            {
                this.standortField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StandortSpecified
        {
            get
            {
                return this.standortField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.standortField = null;
                }
            }
        }
        
        /// <summary>
        /// Nur DU:  BR WB KB VZ BB PK
        /// </summary>
        public MaterialArtType MaterialArt
        {
            get
            {
                if (this.materialArtField.HasValue)
                {
                    return this.materialArtField.Value;
                }
                else
                {
                    return default(MaterialArtType);
                }
            }
            set
            {
                this.materialArtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaterialArtSpecified
        {
            get
            {
                return this.materialArtField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.materialArtField = null;
                }
            }
        }
    }
    
    /// <summary>
    /// Gueltige TKS-Standorte.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.thyssen.com/xml/schema/qbic")]
    public enum StandortType
    {
        
        BO,
        
        DO,
        
        DU,
    }
    
    /// <summary>
    /// Zusaetzliche Kennzeichnung von Duisburger Material.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.thyssen.com/xml/schema/qbic")]
    public enum MaterialArtType
    {
        
        /// <summary>
        /// Bramme
        /// </summary>
        BR,
        
        /// <summary>
        /// Warmband
        /// </summary>
        WB,
        
        /// <summary>
        /// Kaltband
        /// </summary>
        KB,
        
        /// <summary>
        /// verzinktes Material
        /// </summary>
        VZ,
        
        /// <summary>
        /// bandbeschichtetes Material
        /// </summary>
        BB,
        
        /// <summary>
        /// Paket (Material zum Versand)
        /// </summary>
        PK,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.thyssen.com/xml/schema/qbic")]
    public partial class Raster1DType
    {
        
        /// <summary>
        /// Anz. der Werte, wird berechnet wenn fehlend.
        /// </summary>
        public int AnzahlX { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnzahlXSpecified { get; set; }
        /// <summary>
        /// Schrittlaenge zwischen zwei Messpunkten, in der spez. x-Richtung und Dimension (Sekunde oder Meter)
        /// </summary>
        public double SegmentgroesseX { get; set; }
        /// <summary>
        /// Darf weggelassen werden, dann wird 0 angenommen.
        /// </summary>
        public double SegmentOffsetX { get; set; }
        public string WerteX { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.thyssen.com/xml/schema/qbic")]
    public partial class StatistikType
    {
        
        public double Min { get; set; }
        public double Max { get; set; }
        public double Avg { get; set; }
        public double StdDev { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.thyssen.com/xml/schema/qbic")]
    public partial class SpurType
    {
        
        private object itemField;
        
        private System.Nullable<WerteTypeEnum> typField;
        
        [System.Xml.Serialization.XmlElementAttribute("Einheit", typeof(EinheitEnum))]
        [System.Xml.Serialization.XmlElementAttribute("EinheitLokal", typeof(string))]
        public object Item { get; set; }
        /// <summary>
        /// Name der Messreihe im statischen Modell
        /// </summary>
        public string Bezeichner { get; set; }
        /// <summary>
        /// Darf weggelassen werden; dann werden die Werte berechnet.
        /// </summary>
        public StatistikType Statistik { get; set; }
        /// <summary>
        /// Richtung der x-Achse (oder Dimension Zeit)
        /// </summary>
        public BezugDimensionEnum DimensionX { get; set; }
        public Raster1DType Raster1D { get; set; }
        
        /// <summary>
        /// SpurType class constructor
        /// </summary>
        public SpurType()
        {
            this.Raster1D = new Raster1DType();
            this.Statistik = new StatistikType();
            this.DimensionX = BezugDimensionEnum.Laenge;
        }
        
        /// <summary>
        /// Neben den Datenspuren koennen z.B. stat. Daten oder Validitaetsflags vorliegen. Falls fehlend, wird der Typ Daten angenommen.
        /// </summary>
        public WerteTypeEnum Typ
        {
            get
            {
                if (this.typField.HasValue)
                {
                    return this.typField.Value;
                }
                else
                {
                    return default(WerteTypeEnum);
                }
            }
            set
            {
                this.typField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypSpecified
        {
            get
            {
                return this.typField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.typField = null;
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.thyssen.com/xml/schema/qbic")]
    public enum EinheitEnum
    {
        
        mm,
        
        mikrom,
        
        gradC,
        
        [System.Xml.Serialization.XmlEnumAttribute("m/min")]
        mmin,
        
        kW,
        
        A,
        
        V,
        
        [System.Xml.Serialization.XmlEnumAttribute("g/qm")]
        gqm,
        
        Prozent,
        
        KN,
        
        mbar,
        
        grad,
        
        [System.Xml.Serialization.XmlEnumAttribute("Keine/1")]
        Keine1,
        
        min,
        
        m,
        
        Test,
        
        [System.Xml.Serialization.XmlEnumAttribute("As/qm")]
        Asqm,
        
        [System.Xml.Serialization.XmlEnumAttribute("m/qs")]
        mqs,
        
        [System.Xml.Serialization.XmlEnumAttribute("U/min")]
        Umin,
        
        MPa,
        
        KNm,
        
        Hz,
        
        [System.Xml.Serialization.XmlEnumAttribute("gradC/s")]
        gradCs,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.thyssen.com/xml/schema/qbic")]
    public enum WerteTypeEnum
    {
        
        Daten,
        
        Validitaet,
        
        Minimum,
        
        Maximum,
        
        StdDev,
        
        Test,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.thyssen.com/xml/schema/qbic")]
    public enum BezugDimensionEnum
    {
        
        Zeit,
        
        Laenge,
        
        Breite,
        
        Dicke,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.thyssen.com/xml/schema/qbic")]
    public partial class MessungType
    {
        
        private BandlaufrichtungEnum bandlaufrichtungField;
        
        private System.Nullable<MessungTypeEnum> messgroesseField;
        
        public string IDMessgeraet { get; set; }
        /// <summary>
        /// z.B. BEFB02
        /// </summary>
        public string Aggregat { get; set; }
        public BandlaufrichtungEnum Bandlaufrichtung { get; set; }
        public bool Endprodukt { get; set; }
        public System.DateTime Messzeitpunkt { get; set; }
        [System.Xml.Serialization.XmlElementAttribute("Spur")]
        public List<SpurType> Spur { get; set; }
        
        /// <summary>
        /// MessungType class constructor
        /// </summary>
        public MessungType()
        {
            this.Spur = new List<SpurType>();
        }
        
        public MessungTypeEnum Messgroesse
        {
            get
            {
                if (this.messgroesseField.HasValue)
                {
                    return this.messgroesseField.Value;
                }
                else
                {
                    return default(MessungTypeEnum);
                }
            }
            set
            {
                this.messgroesseField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MessgroesseSpecified
        {
            get
            {
                return this.messgroesseField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.messgroesseField = null;
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.thyssen.com/xml/schema/qbic")]
    public enum BandlaufrichtungEnum
    {
        
        InWalzRichtung,
        
        GegenWalzRichtung,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.thyssen.com/xml/schema/qbic")]
    public enum MessungTypeEnum
    {
        
        Laenge,
        
        Temperatur,
        
        Geschwindigkeit,
        
        Leistung,
        
        Strom,
        
        Spannung,
        
        Zinkauflage,
        
        Eisenanteil,
        
        Taupunkt,
        
        Dressiergrad,
        
        Winkel,
        
        Kraft,
        
        Streckgrad,
        
        Zugfestigkeit,
        
        Druck,
        
        Einoelgrad,
        
        Test,
    }
}
