; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
;!define PRODUCT_VERSION "1.25.0"
;!define PRODUCT_FILE_VERSION "1.25.0.0"
;!define DO_UNINSTALLER_SIGNING use this to generate and use a signed uninstaller. This also requires SIGN_TOOL, SIGN_CERT, SIGN_PASS and optional SIGN_TIMESTAMP_URL
;!define UNINSTALLER_ONLY use this to generate the uninstaller

!ifndef PRODUCT_VERSION
!define PRODUCT_VERSION "2.0.0 TEST"
!define PRODUCT_FILE_VERSION "2.0.0.0"
!endif

!ifdef DO_UNINSTALLER_SIGNING
;Section to generate uninstaller and sign it.
;This actually calls the same script again with the UNINSTALLER_ONLY define set.
;After the special installer is created it is run and the uninstaller is signed

!verbose push
!verbose 4

!echo "Creating installer with unsigned uninstaller"
!system '"${NSISDIR}\makensis" /V2 /DUNINSTALLER_ONLY /D"PRODUCT_VERSION=${PRODUCT_VERSION}" /D"PRODUCT_FILE_VERSION=${PRODUCT_FILE_VERSION}" ${__FILE__}' = 0

!echo "Executing installer with unsigned uninstaller"
!system "..\InstallFiles\uninstaller_only.exe" = 2
!delfile "..\InstallFiles\uninstaller_only.exe"

!echo "Signing uninstaller"
!ifdef SIGN_TIMESTAMP_URL
!system '"${SIGN_TOOL}" sign /f "${SIGN_CERT}" /p ${SIGN_PASS} /t ${SIGN_TIMESTAMP_URL} ..\InstallFiles\uninst.exe' = 0
!elseB
!system '"${SIGN_TOOL}" sign /f "${SIGN_CERT}" /p ${SIGN_PASS} ..\InstallFiles\uninst.exe' = 0
!endif

!verbose pop

!endif
!define PRODUCT_NAME "ibaDatCoordinator"
!define PRODUCT_PUBLISHER "iba ag"
!define PRODUCT_WEB_SITE "http://www.iba-ag.com"
;!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\ibaPda.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; .NET Framework
; English
!define BASE_URL http://download.microsoft.com/download
!define URL_DOTNET "${BASE_URL}/5/6/7/567758a3-759e-473e-bf8f-52154438565a/dotnetfx.exe"

!include "MUI.nsh"
!include "WinMessages.nsh"
;!define LOGICLIB_STRCMP
!include "LogicLib.nsh"
!include "sections.nsh"
!include "StrFunc.nsh"
!include "Include\InstallHistory.nsh"

;!ifndef UNINSTALLER_ONLY
!include "Include\InstallCrt.nsh"
;!endif

!include WordFunc.nsh
!insertmacro VersionCompare

!addplugindir .

!ifdef UNINSTALLER_ONLY
SetCompress off
!else
SetCompressor /SOLID lzma
!endif

;--------------------------------
;General Interface settings

!define MUI_ICON    "Graphics\ibaInstall.ico"
!define MUI_UNICON  "Graphics\ibaUnInstall.ico"

;--------------------------------
;Interface settings

!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP "Graphics\MUIInstallLogo.bmp"
!define MUI_WELCOMEFINISHPAGE_BITMAP "Graphics\ibaWizard.bmp"
!define MUI_ABORTWARNING
!define MUI_COMPONENTSPAGE_NODESC
!define MUI_WELCOMEFINISHPAGE_INI "welcome.ini"
;!define MUI_COMPONENTSPAGE_SMALLDESC
;!define MUI_FINISHPAGE_NOAUTOCLOSE

;--------------------------------
; Language Selection Dialog Settings

;Remember the installer language
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "Installer Language"

Function OnEnd
  ReadRegStr $0 ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Server"
  ${If} $0 == "1"
  ${OrIf} $0 == "2"
    Exec '"$INSTDIR\ibaDatCoordinator.exe" /service'
  ${Else}
    Exec '"$INSTDIR\ibaDatCoordinator.exe"'
  ${EndIf}
FunctionEnd

;--------------------------------
; Install pages

Page custom PreInstall
!define MUI_WELCOMEPAGE_TITLE_3LINES
;!define MUI_PAGE_CUSTOMFUNCTION_PRE "DisableBackButton"
!insertmacro MUI_PAGE_WELCOME
Page custom InstalltypeSelect
Page custom ServiceAccountPage
;!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!define MUI_FINISHPAGE_TITLE_3LINES
!define MUI_FINISHPAGE_RUN
!define MUI_FINISHPAGE_RUN_FUNCTION "OnEnd"
!insertmacro MUI_PAGE_FINISH

!ifndef DO_UNINSTALLER_SIGNING
;--------------------------------
; Uninstall pages

!define MUI_WELCOMEPAGE_TITLE_3LINES
!insertmacro MUI_UNPAGE_WELCOME
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!define MUI_FINISHPAGE_TITLE_3LINES
!insertmacro MUI_UNPAGE_FINISH
!endif

;--------------------------------
; Languages

!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "German"
!insertmacro MUI_LANGUAGE "French"

;--------------------------------
; General

Name "${PRODUCT_NAME} v${PRODUCT_VERSION}"
!ifdef UNINSTALLER_ONLY
OutFile "..\InstallFiles\uninstaller_only.exe"
!else
OutFile "ibaDatCoordinatorInstall_v${PRODUCT_VERSION}.exe"
!endif
InstallDir "$PROGRAMFILES\iba\ibaDatCoordinator"
;InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails hide
ShowUnInstDetails hide
BrandingText "iba AG"

!define /date CurrentYear "%Y"
VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductName" "${PRODUCT_NAME}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "Comments" ""
VIAddVersionKey /LANG=${LANG_ENGLISH} "CompanyName" "${PRODUCT_PUBLISHER}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "LegalTrademarks" ""
VIAddVersionKey /LANG=${LANG_ENGLISH} "LegalCopyright" "© 2006-${CurrentYear} by iba AG"
VIAddVersionKey /LANG=${LANG_ENGLISH} "FileDescription" "${PRODUCT_NAME} installer"
VIAddVersionKey /LANG=${LANG_ENGLISH} "FileVersion" "${PRODUCT_VERSION}"
VIProductVersion "${PRODUCT_FILE_VERSION}"

;--------------------------------
; Reserve Files

ReserveFile "serviceorstandalone.ini"
;ReserveFile "welcome.ini"
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS
!insertmacro MUI_RESERVEFILE_LANGDLL

${StrLoc}

VAR WinVer
VAR PrevUninstall
Var StartMenuFolder
Var ServiceUserName
Var ServicePassword


InstType "service"
InstType "standalone"

;--------------------------------
; Initialization functions
Function .onInit
  SetShellVarContext all
  
!ifdef UNINSTALLER_ONLY

  WriteUninstaller "$EXEDIR\..\InstallFiles\uninst.exe"
  Quit
  
!else
  
  !insertmacro MUI_INSTALLOPTIONS_EXTRACT "serviceorstandalone.ini"
  ${If} $LANGUAGE == 1031       ;German
    !insertmacro MUI_INSTALLOPTIONS_EXTRACT_AS "ServiceAccount_de.ini" "ServiceAccount.ini"
  ${ElseIf} $LANGUAGE == 1036   ;French
    !insertmacro MUI_INSTALLOPTIONS_EXTRACT_AS "ServiceAccount_fr.ini" "ServiceAccount.ini"
  ${Else}
    !insertmacro MUI_INSTALLOPTIONS_EXTRACT_AS "ServiceAccount_en.ini" "ServiceAccount.ini"
  ${EndIf}
  ;!insertmacro MUI_INSTALLOPTIONS_EXTRACT "welcome.ini"
  ;Display language selection dialog
  ;!insertmacro MUI_LANGDLL_DISPLAY

  ;In case of a silent install call the PreInstall function directly
  IfSilent +1 +2
    Call PreInstall
!endif
FunctionEnd

!ifndef DO_UNINSTALLER_SIGNING
Function un.onInit
  ;!insertmacro MUI_UNGETLANGUAGE
FunctionEnd
!endif

;--------------------------------
; PreInstall function that checks requirements and previous installs
; Remark : This is done in separate "dummy" page because initialization functions
;          don't support translated error messages

Function PreInstall
  Call CheckRequirements
  Call CheckPreviousVersions

  ${If} $WinVer == "Win8"
  ${OrIf} $WinVer == "Win8.1"
    StrCpy $StartMenuFolder "ibaDatCoordinator" 
  ${Else}
    StrCpy $StartMenuFolder "iba\ibaDatCoordinator"
  ${EndIf}

FunctionEnd


;--------------------------------
; Requirements check

Function CheckRequirements
  ;Check that operating system is supported
  Call GetWindowsVersion
  Pop $WinVer
  StrCmp $WinVer "2000" OSisOk +1
  StrCmp $WinVer "XP" OSisOK +1
  StrCmp $WinVer "2003" OSisOK +1
  StrCmp $WinVer "2008" OSisOK +1
  StrCmp $WinVer "win7" OSisOK +1
  StrCmp $WinVer "win8" OSisOK +1
  StrCmp $WinVer "win8.1" OSisOK +1
    MessageBox MB_OK|MB_ICONSTOP $(TEXT_OS_NOT_SUPPORTED)
    Quit
  OSisOk:

  ;Check user has administrator rights
  UserInfo::GetName
  Pop $0
  UserInfo::GetAccountType
  Pop $1
  StrCmp $1 "Admin" adminOK +1
    MessageBox MB_OK|MB_ICONSTOP $(TEXT_NOT_ADMINISTRATOR)
    Quit
  adminOK:

  ;Check if required .NET framework version is installed
  Call GetDotNETVersion
  Pop $0
  Pop $1

  ;Check if .NET framework 4.0 full is installed
  ${VersionCompare} $0 "4.5.2" $2
  ${If} $2 == 2
    ;Framework 4.5.2 not found --> stop installer
    MessageBox MB_OK|MB_ICONSTOP|MB_SETFOREGROUND $(TEXT_FRAMEWORK_MISSING)
    Quit
  ${EndIf}  

FunctionEnd

;--------------------------------
; Check if previous version of ibaDatCoordinator are installed

Function CheckPreviousVersions

  StrCpy $PrevUninstall ""
  StrCpy $ServiceUserName ""
  StrCpy $ServicePassword ""

  ;Check if previous install found
  ReadRegStr $0 ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion"
  ${If} $0 != ""

    ;Retrieve version number from string
    Push $0
    Call GetVersionNr
    Pop $R0
    Push "${PRODUCT_VERSION}"
    Call GetVersionNr
    Pop $R1
    IntCmp $R0 $R1 sameVersion olderVersion newerVersion

    sameVersion:
    ;Same version is already installed --> ask to re-install
    MessageBox MB_YESNO|MB_ICONSTOP $(TEXT_ALREADY_INSTALLED) /SD IDYES IDYES upgrade IDNO quit

    olderVersion:
    ;Older version is installed --> ask to upgrade
    MessageBox MB_YESNO|MB_ICONQUESTION $(TEXT_OLDER_INSTALLED) /SD IDYES IDYES upgrade IDNO quit

    newerVersion:
    ;Newer version is installed --> quit (manual uninstall is needed)
    MessageBox MB_OK|MB_ICONSTOP $(TEXT_NEWER_INSTALLED)
    Quit
  ${Else}
    Goto end
  ${EndIf}


  quit:
  Quit

  upgrade:
  ReadRegStr $INSTDIR ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "InstallDir"
  ReadRegStr $0 ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString"
  ReadRegStr $ServiceUserName ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Service1" ;Retrieve user name
  ReadRegStr $ServicePassword ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Service2" ;Retrieve password
  StrCpy $PrevUninstall '"$0" /S _?=$INSTDIR'  ;add silent parameter switch to uninstall string

  end:
FunctionEnd

;--------------------------------
; Uninstall previous version section

Section -PreInstall
  !insertmacro WriteToInstallHistory "Installing ${PRODUCT_NAME} v${PRODUCT_VERSION} (Command line: $CMDLINE)"

  ${If} $PrevUninstall != ""
    ;Uninstall previous version
    DetailPrint $(TEXT_PREV_UNINSTALLING)
    nsExec::Exec $PrevUninstall
  ${EndIf}
  
  ;Install VC++ 2015 runtime
  !insertmacro InstallCRT14_x86
  
SectionEnd

Section $(DESC_DATCOOR_NOSERVICE) DATCOOR_NOSERVICE
  SetOverwrite on
  ;MessageBox MB_OK "Debug in DATCOOR_NOSERVICE (1)"
  ;Copy server files
  SetOutPath "$INSTDIR"
  File "..\Dependencies\ibaFilesLiteInstall.exe"
  File "..\Dependencies\ibaLogger.dll"
  File "..\Dependencies\Eyefinder.dll"
  File "..\Dependencies\DotNetMagic2005.DLL"
  File "..\Dependencies\DotNetMagic.DLL"
  File "..\Dependencies\ICSharpCode.TextEditor.dll"
  File "..\Dependencies\ICSharpCode.SharpZipLib.dll"
  File "..\Dependencies\msvcr100.dll"
  File "..\Dependencies\msvcp100.dll"
  File "..\Dependencies\PowerCollections.dll"
  File "..\Dependencies\ibaFilesLiteDotNet.dll"
  ;HD-stuff
  File "..\InstallFiles\Protected\hdCore.dll"
  File "..\InstallFiles\Protected\hdClient.dll"
  File "..\InstallFiles\Obfuscated\hdClientFiles.dll"
  File "..\Dependencies\hdCommon.dll"
  File "..\Dependencies\hdProtoBuf.dll"
  File "..\Dependencies\hdClientInterfaces.dll"
  
  File "..\Dependencies\DevExpress.XtraEditors.v16.1.dll"
  File "..\Dependencies\DevExpress.XtraGrid.v16.1.dll"
  File "..\Dependencies\DevExpress.Data.v16.1.dll"
  File "..\Dependencies\DevExpress.Utils.v16.1.dll"
  File "..\Dependencies\DevExpress.Sparkline.v16.1.Core.dll"
  File "..\Dependencies\DevExpress.Printing.v16.1.Core.dll"
  
  File "..\ibaDatCoordinator\bin\Release\Interop.ibaFilesLiteLib.dll"
  File "..\InstallFiles\Protected\ibaDatCoordinator.exe"

  File "..\InstallFiles\Protected\DatCoUtil.dll"
  File "..\ibaDatCoordinator\Resources\default.ico"
  File "..\DatCoordinatorPlugins\bin\Release\DatCoordinatorPlugins.dll"
  File "versions_dat.htm"
  
  ; runtime
  File "..\InstallFiles\Protected\ibaRuntime.dll"
  
  ; dongle viewer
  SetOutPath "$INSTDIR"
  File "..\Dependencies\ibaDongleViewerSetup.exe"
  nsExec::Exec '"$INSTDIR\ibaDongleViewerSetup.exe" /S'
  Delete "$INSTDIR\ibaDongleViewerSetup.exe"
  ;help files
  File "..\iDatCo_HTML_Help\*.chm"
  ;localisation
  SetOutPath "$INSTDIR\de"
  File "..\Passolo\de\ibaDatCoordinator.resources.dll"
  File "..\InstallFiles\Obfuscated\de\hdClient.resources.dll"
  File "..\Dependencies\de\hdCommon.resources.dll"
  ;File "..\Dependencies\de\hd_plugin.resources.dll"
  SetOutPath "$INSTDIR\fr"
  File "..\Passolo\fr\ibaDatCoordinator.resources.dll"
  File "..\InstallFiles\Obfuscated\fr\hdClient.resources.dll"
  File "..\Dependencies\fr\hdCommon.resources.dll"
  ;File "..\Dependencies\fr\hd_plugin.resources.dll"
  ;;plugins
  ;SetOutPath "$INSTDIR\plugins"
  ;File "..\Dependencies\hd_plugin.dll"
  
  ;Install ibaFiles
  DetailPrint $(TEXT_IBAFILES_INSTALL)
  nsExec::Exec '"$INSTDIR\ibaFilesLiteInstall.exe" /S'

  SetOutPath "$INSTDIR"
  ;Create uninstall shortcut

  
  CreateDirectory "$SMPROGRAMS\$StartMenuFolder"
  CreateShortCut "$SMPROGRAMS\$StartMenuFolder\ibaDatCoordinator.lnk" "$INSTDIR\ibaDatCoordinator.exe" "" "$INSTDIR\default.ico"
  CreateDirectory "%LOCALAPPDATA%\iba\ibaDatCoordinator"
  CreateShortCut "$SMPROGRAMS\$StartMenuFolder\$(TEXT_LOG_FILES).lnk" "$LOCALAPPDATA\iba\ibaDatCoordinator"
  
  ;MessageBox MB_OK "Debug Writing 0"
  
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Server" "0"
  !insertmacro WriteToInstallHistory "Finished installing stand alone version of ${PRODUCT_NAME} v${PRODUCT_VERSION}"
SectionEnd

Section $(DESC_DATCOOR_SERVICE) DATCOOR_SERVICE
  SetOverwrite on
  
  ;MessageBox MB_OK "Debug in DATCOOR_SERVICE (2)"
  ;Copy server files
  SetOutPath "$INSTDIR"
  File "..\Dependencies\ibaFilesLiteInstall.exe"
  File "..\Dependencies\ibaLogger.dll"
  File "..\Dependencies\Eyefinder.dll"
  File "..\Dependencies\DotNetMagic2005.DLL"
  File "..\Dependencies\DotNetMagic.DLL"
  File "..\Dependencies\ICSharpCode.TextEditor.dll"
  File "..\Dependencies\ICSharpCode.SharpZipLib.dll"
  File "..\Dependencies\msvcr100.dll"
  File "..\Dependencies\msvcp100.dll"
  File "..\Dependencies\ibaFilesLiteDotNet.dll"
  File "..\Dependencies\PowerCollections.dll"
  ;HD-stuff
  File "..\InstallFiles\Protected\hdCore.dll"
  File "..\InstallFiles\Protected\hdClient.dll"
  File "..\InstallFiles\Obfuscated\hdClientFiles.dll"
  File "..\Dependencies\hdCommon.dll"
  File "..\Dependencies\hdProtoBuf.dll"
  File "..\Dependencies\hdClientInterfaces.dll"

  File "..\Dependencies\DevExpress.XtraEditors.v16.1.dll"
  File "..\Dependencies\DevExpress.XtraGrid.v16.1.dll"
  File "..\Dependencies\DevExpress.Data.v16.1.dll"
  File "..\Dependencies\DevExpress.Utils.v16.1.dll"
  File "..\Dependencies\DevExpress.Sparkline.v16.1.Core.dll"
  File "..\Dependencies\DevExpress.Printing.v16.1.Core.dll"
  File "..\ibaDatCoordinator\bin\Release\Interop.ibaFilesLiteLib.dll"
  File "..\InstallFiles\Protected\ibaDatCoordinator.exe"

  File "..\ibaDatCoordinator\bin\Release\DatCoUtil.dll"
  File "..\ibaDatCoordinator\Resources\running.ico"
  File "..\ibaDatCoordinator\Resources\DatCo_SrvStat_Icon_pure.ico"
  File "..\DatCoordinatorPlugins\bin\Release\DatCoordinatorPlugins.dll"
  File "..\InstallFiles\Protected\ibaDatCoordinatorService.exe"
  File "versions_dat.htm"
  File "Copy_Printer_Settings_To_System_Account.bat"
  File "createundoregfile.bat"
  ; runtime
  File "..\InstallFiles\Protected\ibaRuntime.dll"
  ; dongle viewer
  SetOutPath "$INSTDIR"
  File "..\Dependencies\ibaDongleViewerSetup.exe"
  nsExec::Exec '"$INSTDIR\ibaDongleViewerSetup.exe" /S'
  Delete "$INSTDIR\ibaDongleViewerSetup.exe"
  ;help files
  File "..\iDatCo_HTML_Help\*.chm"
  ;localisation
  SetOutPath "$INSTDIR\de"
  File "..\Passolo\de\ibaDatCoordinator.resources.dll"
  File "..\InstallFiles\Obfuscated\de\hdClient.resources.dll"
  File "..\Dependencies\de\hdCommon.resources.dll"
  ;File "..\Dependencies\de\hd_plugin.resources.dll"
  SetOutPath "$INSTDIR\fr"
  File "..\Passolo\fr\ibaDatCoordinator.resources.dll"
  File "..\InstallFiles\Obfuscated\fr\hdClient.resources.dll"
  File "..\Dependencies\fr\hdCommon.resources.dll"
  ;File "..\Dependencies\fr\hd_plugin.resources.dll"
  ;;plugins
  ;SetOutPath "$INSTDIR\plugins"
  ;File "..\Dependencies\hd_plugin.dll"
  
  ;Install ibaFiles
  DetailPrint $(TEXT_IBAFILES_INSTALL)
  nsExec::Exec '"$INSTDIR\ibaFilesLiteInstall.exe" /S'
  
  DetailPrint $(TEXT_SERVICE_INSTALL)
  !insertmacro MUI_INSTALLOPTIONS_READ $R0 "ServiceAccount.ini" "Field 2" "State" ;local system
  ${If} $R0 == "1"
    StrCpy $ServiceUserName ""
    StrCpy $ServicePassword ""
  ${Else}
    !insertmacro MUI_INSTALLOPTIONS_READ $ServiceUserName "ServiceAccount.ini" "Field 5" "State" ;user name
    !insertmacro MUI_INSTALLOPTIONS_READ $ServicePassword "ServiceAccount.ini" "Field 7" "State" ;password
  ${EndIf}
  nsSCMEx::Install /NOUNLOAD "ibaDatCoordinatorService" "iba DatCoordinator Service" 0x010 2 "$INSTDIR\ibaDatCoordinatorService.exe" "" "" $ServiceUserName $ServicePassword
  Pop $R0
  ${If} $R0 != "success"
    Pop $R0
    MessageBox MB_OK|MB_ICONSTOP "Error installing service, error code $R0" 
  ${EndIf}
  
  ;MessageBox MB_OK "Debug Writing 1"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Server" "1"
  ;Save username and password
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Service1" $ServiceUserName
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Service2" $ServicePassword

  ;Add serverstatus to autorun
  WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Run" "ibaDatCoordinator service status" "$INSTDIR\ibaDatCoordinator.exe /status"

  ;printer stuff
  SetOutPath "$INSTDIR"
  nsExec::Exec '"$INSTDIR\createundoregfile.bat"'
  nsExec::Exec '"$INSTDIR\Copy_Printer_Settings_To_System_Account.bat"'
  Delete "$INSTDIR\createundoregfile.bat"
  nsSCMEx::Stop /NOUNLOAD "Spooler"
  nsSCMEx::Start /NOUNLOAD "Spooler"

  ;add firewall exceptions...
  nsSCMEx::FirewallIsAvailable
  Pop $R0
  ${If} $R0 == "1"
    DetailPrint $(TEXT_CONFIGURE_FIREWALL)
    nsSCMEx::FirewallAddApplication /NOUNLOAD "$INSTDIR\ibaDatCoordinator.exe" "ibaDatCoordinator client or status"
    nsSCMEx::FirewallAddApplication /NOUNLOAD "$INSTDIR\ibaDatCoordinatorService.exe" "ibaDatCoordinator server"
  ${EndIf}
  
  ;shortcut
  CreateDirectory "$SMPROGRAMS\$StartMenuFolder"
  CreateShortCut "$SMPROGRAMS\$StartMenuFolder\ibaDatCoordinator Server Status.lnk" "$INSTDIR\ibaDatCoordinator.exe" "/status" "$INSTDIR\DatCo_SrvStat_Icon_pure.ico"
  CreateShortCut "$SMPROGRAMS\$StartMenuFolder\ibaDatCoordinator Client.lnk" "$INSTDIR\ibaDatCoordinator.exe" "/service" "$INSTDIR\running.ico"
  CreateDirectory "$APPDATA\iba\ibaDatCoordinator"
  CreateShortCut "$SMPROGRAMS\$StartMenuFolder\$(TEXT_LOG_FILES).lnk" "$APPDATA\iba\ibaDatCoordinator"
  ;Start service
   nsSCMEx::Start /NOUNLOAD "ibaDatCoordinatorService"
  ;Start service status
   Exec '"$INSTDIR\ibaDatCoordinator.exe" /status'
   !insertmacro WriteToInstallHistory "Finished installing client-server version of ${PRODUCT_NAME} v${PRODUCT_VERSION}"
SectionEnd

Section $(DESC_DATCOOR_CLIENT) DATCOOR_CLIENT
  SetOverwrite on
  ;MessageBox MB_OK "Debug in DATCOOR_CLIENT(3)"
  ;Copy server files
  SetOutPath "$INSTDIR"
  File "..\Dependencies\ibaFilesLiteInstall.exe"
  File "..\Dependencies\ibaLogger.dll"
  File "..\Dependencies\Eyefinder.dll"
  File "..\Dependencies\DotNetMagic2005.DLL"
  File "..\Dependencies\DotNetMagic.DLL"
  File "..\Dependencies\msvcr100.dll"
  File "..\Dependencies\msvcp100.dll"  
  File "..\Dependencies\ICSharpCode.TextEditor.dll"
  File "..\Dependencies\ICSharpCode.SharpZipLib.dll"
  File "..\Dependencies\msvcr100.dll"
  File "..\Dependencies\msvcp100.dll"  
;HD-stuff
  File "..\InstallFiles\Protected\hdClient.dll"
  File "..\Dependencies\hdClientInterfaces.dll"
  File "..\Dependencies\hdCommon.dll"
  File "..\Dependencies\DevExpress.XtraEditors.v16.1.dll"
  File "..\Dependencies\DevExpress.XtraGrid.v16.1.dll"
  File "..\Dependencies\DevExpress.Data.v16.1.dll"
  File "..\Dependencies\DevExpress.Utils.v16.1.dll"
  File "..\Dependencies\DevExpress.Sparkline.v16.1.Core.dll"
  File "..\Dependencies\DevExpress.Printing.v16.1.Core.dll"
  
  File "..\ibaDatCoordinator\bin\Release\Interop.ibaFilesLiteLib.dll"
  File "..\InstallFiles\Protected\ibaDatCoordinator.exe"

  File "..\InstallFiles\Protected\DatCoUtil.dll"
  File "..\ibaDatCoordinator\Resources\default.ico"
  File "..\DatCoordinatorPlugins\bin\Release\DatCoordinatorPlugins.dll"
  File "versions_dat.htm"
  
  ; runtime
  File "..\InstallFiles\Protected\ibaRuntime.dll"
  
  ; dongle viewer
  SetOutPath "$INSTDIR"
  File "..\Dependencies\ibaDongleViewerSetup.exe"
  nsExec::Exec '"$INSTDIR\ibaDongleViewerSetup.exe" /S'
  Delete "$INSTDIR\ibaDongleViewerSetup.exe"
  ;help files
  File "..\iDatCo_HTML_Help\*.chm"
  ;localisation
  SetOutPath "$INSTDIR\de"
  File "..\Passolo\de\ibaDatCoordinator.resources.dll"
  File "..\InstallFiles\Obfuscated\de\hdClient.resources.dll"
  SetOutPath "$INSTDIR\fr"
  File "..\Passolo\fr\ibaDatCoordinator.resources.dll"
  File "..\InstallFiles\Obfuscated\fr\hdClient.resources.dll"

  ;Install ibaFiles
  DetailPrint $(TEXT_IBAFILES_INSTALL)
  nsExec::Exec '"$INSTDIR\ibaFilesLiteInstall.exe" /S'

  SetOutPath "$INSTDIR"
  ;Create uninstall shortcut

    ;add firewall exceptions...
  nsSCMEx::FirewallIsAvailable
  Pop $R0
  ${If} $R0 == "1"
    DetailPrint $(TEXT_CONFIGURE_FIREWALL)
    nsSCMEx::FirewallAddApplication /NOUNLOAD "$INSTDIR\ibaDatCoordinator.exe" "ibaDatCoordinator client or status"
  ${EndIf}
  
  CreateDirectory "$SMPROGRAMS\$StartMenuFolder"
  CreateShortCut "$SMPROGRAMS\$StartMenuFolder\ibaDatCoordinator Client.lnk" "$INSTDIR\ibaDatCoordinator.exe" "/service" "$INSTDIR\default.ico"
  CreateDirectory "%LOCALAPPDATA%\iba\ibaDatCoordinator"
  CreateShortCut "$SMPROGRAMS\$StartMenuFolder\$(TEXT_LOG_FILES).lnk" "$LOCALAPPDATA\iba\ibaDatCoordinator"
  
  ;MessageBox MB_OK "Debug writing 2"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Server" "2"
  !insertmacro WriteToInstallHistory "Finished installing stand alone version of ${PRODUCT_NAME} v${PRODUCT_VERSION}"
SectionEnd

Section -Post

!ifdef DO_UNINSTALLER_SIGNING
  SetOutPath $INSTDIR
  File "..\InstallFiles\uninst.exe"
!else
  WriteUninstaller "$INSTDIR\uninst.exe"
!endif

  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\ibaDatCoordinator.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "HelpLink" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "InstallDir" "$INSTDIR"
  WriteRegDWORD ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "NoModify" 1
  WriteRegDWORD ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "NoRepair" 1
  CreateDirectory "$SMPROGRAMS\$StartMenuFolder"
  CreateShortCut "$SMPROGRAMS\$StartMenuFolder\$(TEXT_UNINSTALL).lnk" "$INSTDIR\uninst.exe"

  IfSilent +1 +2
    Exec '"$INSTDIR\ibaDatCoordinator.exe" /service'

SectionEnd

Function InstalltypeSelect
  !insertmacro MUI_INSTALLOPTIONS_WRITE "serviceorstandalone.ini" "Field 1" "Text" "$(TEXT_INSTALLSTANDALONE)"
  !insertmacro MUI_INSTALLOPTIONS_WRITE "serviceorstandalone.ini" "Field 2" "Text" "$(TEXT_INSTALLSERVICE)"
  !insertmacro MUI_INSTALLOPTIONS_WRITE "serviceorstandalone.ini" "Field 3" "Text" "$(TEXT_INSTALLCLIENT)"
  !insertmacro MUI_HEADER_TEXT "$(TEXT_SERVICEORSTANDALONE_TITLE)" "$(TEXT_SERVICEORSTANDALONE_SUBTITLE)"
  StrCpy $0 "1"
  ReadRegStr $0 ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Server"
  
  ;MessageBox MB_OK $0
  
  ${If} $0 == "0"
    !insertmacro MUI_INSTALLOPTIONS_WRITE "serviceorstandalone.ini" "Field 1" "State" "1"
    !insertmacro MUI_INSTALLOPTIONS_WRITE "serviceorstandalone.ini" "Field 2" "State" "0"
	!insertmacro MUI_INSTALLOPTIONS_WRITE "serviceorstandalone.ini" "Field 3" "State" "0"
  ${ElseIf} $0 == "1"
    !insertmacro MUI_INSTALLOPTIONS_WRITE "serviceorstandalone.ini" "Field 1" "State" "0"
    !insertmacro MUI_INSTALLOPTIONS_WRITE "serviceorstandalone.ini" "Field 2" "State" "1"
	!insertmacro MUI_INSTALLOPTIONS_WRITE "serviceorstandalone.ini" "Field 3" "State" "0"
  ${Else}
    !insertmacro MUI_INSTALLOPTIONS_WRITE "serviceorstandalone.ini" "Field 1" "State" "0"
    !insertmacro MUI_INSTALLOPTIONS_WRITE "serviceorstandalone.ini" "Field 2" "State" "0"
	!insertmacro MUI_INSTALLOPTIONS_WRITE "serviceorstandalone.ini" "Field 3" "State" "1"
  ${EndIf}
  
  
  
  !insertmacro MUI_INSTALLOPTIONS_DISPLAY "serviceorstandalone.ini"
  !insertmacro MUI_INSTALLOPTIONS_READ $0 "serviceorstandalone.ini" "Field 1" "State"
  !insertmacro MUI_INSTALLOPTIONS_READ $1 "serviceorstandalone.ini" "Field 2" "State"
	
 
  SectionGetFlags ${DATCOOR_NOSERVICE} $R0
  ${If} $0 == "1"
    IntOp $R1 $R0 | ${SF_SELECTED}
    SectionSetFlags ${DATCOOR_NOSERVICE} $R1
  ${Else}
    IntOp $R1 $R0 & ~${SF_SELECTED}
    SectionSetFlags ${DATCOOR_NOSERVICE} $R1
  ${EndIf}
  
  SectionGetFlags ${DATCOOR_SERVICE} $R0
  ${If} $1 == "1"
    IntOp $R1 $R0 | ${SF_SELECTED}
    SectionSetFlags ${DATCOOR_SERVICE} $R1
  ${Else}
    IntOp $R1 $R0 & ~${SF_SELECTED}
    SectionSetFlags ${DATCOOR_SERVICE} $R1
  ${EndIf}
  
  SectionGetFlags ${DATCOOR_CLIENT} $R0
  ${If} $0 == "0"
  ${AndIf} $1 == "0"
    IntOp $R1 $R0 | ${SF_SELECTED}
    SectionSetFlags ${DATCOOR_CLIENT} $R1
  ${Else}
    IntOp $R1 $R0 & ~${SF_SELECTED}
    SectionSetFlags ${DATCOOR_CLIENT} $R1
  ${EndIf}
 
FunctionEnd


!ifndef DO_UNINSTALLER_SIGNING
;--------------------------------
; Uninstall section

Section Uninstall

  SetShellVarContext all
  !insertmacro WriteToInstallHistory "Uninstalling ${PRODUCT_NAME} v${PRODUCT_VERSION} (Command line: $CMDLINE)"
  
 ;Remove exceptions from firewall
  nsSCMEx::FirewallIsAvailable
  Pop $R0
  ${If} $R0 == "1"
    DetailPrint $(TEXT_CONFIGURE_FIREWALL)
    nsSCMEx::FirewallRemoveApplication /NOUNLOAD "$INSTDIR\ibaDatCoordinator.exe" "ibaDatCoordinator client or status"
	nsSCMEx::FirewallRemoveApplication /NOUNLOAD "$INSTDIR\ibaDatCoordinatorService.exe" "ibaDatCoordinator server"
  ${EndIf}
  
  ReadRegStr $0 ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Server"
  ${If} $0 == "1"
    Call un.UninstallService
	  ;Log installation
	!insertmacro WriteToInstallHistory "Finished uninstalling service component for ${PRODUCT_NAME} v${PRODUCT_VERSION}"
  ${EndIf}

  Call un.UninstallTasks
  !insertmacro WriteToInstallHistory "Finished uninstalling client component for ${PRODUCT_NAME} v${PRODUCT_VERSION}"

  ;Delete uninstaller
  Delete "$INSTDIR\uninst.exe"

  ;Delete shortcuts
  RMDir /r "$SMPROGRAMS\ibaDatCoordinator"
  RMDir /r "$SMPROGRAMS\iba\ibaDatCoordinator"
  RMDir "$SMPROGRAMS\iba" ;it will only be removed when it is empty

  ;Delete "Add/Remove programs" registry keys
  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  SetAutoClose true
  

  
SectionEnd


Function un.UninstallTasks
  ClearErrors
  Delete "$INSTDIR\ibaDatCoordinator.exe"
  IfErrors 0 +2
    Call un.stillRunning
	
  Delete "$INSTDIR\*.chm"
  Delete "$INSTDIR\ibaLogger.dll"
  Delete "$INSTDIR\Eyefinder.dll"
  Delete "$INSTDIR\DatCoUtil.dll"
  Delete "$INSTDIR\DatCoordinatorPlugins.dll"
  Delete "$INSTDIR\DotNetMagic.dll"
  Delete "$INSTDIR\DotNetMagic2005.dll"
  Delete "$INSTDIR\ibaFilesLiteDotNet.dll"
  
  Delete "$INSTDIR\hdCore.dll"
  Delete "$INSTDIR\hdClient.dll"
  Delete "$INSTDIR\hdClientFiles.dll"
  Delete "$INSTDIR\hdClientInterfaces.dll"
  Delete "$INSTDIR\hdCommon.dll"
  Delete "$INSTDIR\hdProtoBuf.dll"
  Delete "$INSTDIR\PowerCollections.dll"

  Delete "$INSTDIR\DevExpress.XtraEditors.v16.1.dll"
  Delete "$INSTDIR\DevExpress.XtraGrid.v16.1.dll"
  Delete "$INSTDIR\DevExpress.Data.v16.1.dll"
  Delete "$INSTDIR\DevExpress.Utils.v16.1.dll"
  Delete "$INSTDIR\DevExpress.Sparkline.v16.1.Core.dll"
  Delete "$INSTDIR\DevExpress.Printing.v16.1.Core.dll"
  
  Delete "$INSTDIR\Interop.ibaFilesLiteLib.dll"
  Delete "$INSTDIR\ICSharpCode.TextEditor.dll"
  Delete "$INSTDIR\ICSharpCode.SharpZipLib.dll"
  Delete "$INSTDIR\msvcr100.dll"
  Delete "$INSTDIR\msvcp100.dll"
  Delete "$INSTDIR\ibaFilesLiteInstall.exe"
  Delete "$INSTDIR\default.ico"
  Delete "$INSTDIR\default.ico"
  Delete "$INSTDIR\versions_dat.htm"
  Delete "$INSTDIR\Copy_Printer_Settings_To_System_Account.bat"
  Delete "$INSTDIR\createundoregfile.bat"
  ; runtime
  Delete "$INSTDIR\ibaRuntime.dll"
  ;resources
  Delete "$INSTDIR\de\ibaDatCoordinator.resources.dll"
  Delete "$INSTDIR\de\hdClient.resources.dll"
  Delete "$INSTDIR\de\hdCommon.resources.dll"
  Delete "$INSTDIR\de\hd_plugin.resources.dll"
  RMDir "$INSTDIR\de"
  Delete "$INSTDIR\fr\ibaDatCoordinator.resources.dll"
  Delete "$INSTDIR\fr\hdClient.resources.dll"
  Delete "$INSTDIR\fr\hdCommon.resources.dll"
  Delete "$INSTDIR\fr\hd_plugin.resources.dll"
  RMDir "$INSTDIR\fr"
  ;plugins
  Delete "$INSTDIR\plugins\hd_plugin.dll"
  RMDir "$INSTDIR\plugins"
  ;Remove install dir
  RMDir "$INSTDIR"
FunctionEnd

Function un.UninstallService
    ;Trigger close of all server status instances
  DetailPrint $(TEXT_STATUS_STOP)
  WriteRegDWORD HKLM "SOFTWARE\iba\ibaDatCoordinator\Uninstall" "isBusy" 0
  WriteRegDWORD HKLM "SOFTWARE\iba\ibaDatCoordinator\Uninstall" "isBusy" 1
  Sleep 500

  ;Check if server status programs are still running
  StrCpy $R0 "0"
  StrCpy $R1 "10"
  againStatus:
  ClearErrors
  Delete "$INSTDIR\Server\ibaPdaServerStatus.exe"
  IfErrors 0 okStatus
    DetailPrint "Attempt $R0 failed"
    Sleep 1000
    IntOp $R0 $R0 + 1
    IntCmp $R0 $R1 timeoutStatus againStatus
  timeoutStatus:
  StrCpy $R0 "0"
  StrCpy $R1 "1"
  MessageBox MB_RETRYCANCEL|MB_ICONSTOP|MB_SETFOREGROUND $(TEXT_CLOSE_STATUS) IDRETRY againStatus
    Quit
  okStatus:
  
  ;Clear uninstall is busy flag
  WriteRegDWORD HKLM "SOFTWARE\iba\ibaPDA\Uninstall" "isBusy" 0
  
  
  ;uninstall the service

  ;stop statusform
  FindWindow $0 "" "ibaDatCoordinatorStatusCloseForm"
  SendMessage $0 0x8140 0 0
  ${Unless} $0 == 0
    Sleep 1000
    FindWindow $0 "" "ibaDatCoordinatorStatusCloseForm"
  ${EndUnless}

  ;Stop service
  DetailPrint $(TEXT_SERVICE_STOP)
  nsSCMEx::Stop /NOUNLOAD "ibaDatCoordinatorService"

  ;Delete service
  DetailPrint $(TEXT_SERVICE_REMOVE)
  nsSCMEx::Remove /NOUNLOAD "ibaDatCoordinatorService"

  Delete "$INSTDIR\ibaDatCoordinatorService.exe"
  IfErrors 0 +2
    Call un.waitAndDelete

  Delete "$INSTDIR\running.ico"
  Delete "$INSTDIR\DatCo_SrvStat_Icon_pure.ico"
  ;Remove server status from autorun
  DeleteRegValue HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Run" "ibaDatCoordinator service status"
FunctionEnd

Function un.WaitAndDelete
  Sleep 1000
  Delete "$INSTDIR\ibaDatCoordinatorService.exe"
  IfErrors -2 0
FunctionEnd

Function un.StillRunning
  MessageBox MB_ICONSTOP|MB_OK $(TEXT_STILL_RUNNING)
  Abort
FunctionEnd

!endif ;DO_UNINSTALLER_SIGNING

;--------------------------------
; Description of sections

;!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
;  !insertmacro MUI_DESCRIPTION_TEXT ${SECDOTNET}       $(DESC_LONGDOTNET)
;  !insertmacro MUI_DESCRIPTION_TEXT ${DATCOOR_NOSERVICE}   $(DESC_DatCoor_NoService2)
;  !insertmacro MUI_DESCRIPTION_TEXT ${DATCOOR_SERVICE}   $(DESC_DatCoor_Service2)
;!insertmacro MUI_FUNCTION_DESCRIPTION_END


;--------------------------------
; Usefull functions

;--------------------------------
; GetDotNETVersion
;
; Usage:
;   Call GetDotNETVersion
;   Pop $0
;   $0 = "not found" when no .NET framework is installed
;      = "VERSION" with VERSION the version of the .NET framework installed


;Function GetDotNETVersion
;  Push $0
;  Push $1
;
;  System::Call "mscoree::GetCORVersion(w .r0, i ${NSIS_MAX_STRLEN}, *i) i .r1"
;  StrCmp $1 0 +2
;    StrCpy $0 "not found"
;
;  Pop $1
;  Exch $0
;FunctionEnd

Function GetDotNETVersion
  Push $0
  Push $1
  Push $2
  StrCpy $0 ""
  StrCpy $1 ""
  StrCpy $2 ""
  
  ;in x64
  ;ReadRegDWORD $0 HKLM "SOFTWARE\Wow6432node\Microsoft\NET Framework Setup\NDP\v4\Full" "Install"
  
  ;Check if v4.5.2 or higher is installed
  ReadRegDWORD $2 HKLM "SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full" "Install"
  ${If} $2 = 1
    ReadRegDWORD $2 HKLM "SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full" "Release"
    ${If} $2 >= 379893
      StrCpy $0 "4.5.2"  ;4.5.2 or higher
    ${EndIf}
  ${EndIf}
  
  ;Check if v3.5 is installed
  ReadRegDWORD $2 HKLM "SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5" "Install"
  StrCmp $2 "1" +1 +3
  StrCpy $1 "3.5"
  Goto end
  
  ;Check if v3.0 is installed
  ReadRegDWORD $2 HKLM "SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0" "Install"
  StrCmp $2 "1" +1 +3
  StrCpy $1 "3.0"
  Goto end
  
  ;Check if v2.0 is installed
  ReadRegDWORD $2 HKLM "SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727" "Install"
  StrCmp $2 "1" +1 +3
  StrCpy $1 "2.0.50727"
  Goto end
  
  ;Check if v1.1 is installed
  ;ReadRegDWORD $0 HKLM "SOFTWARE\Microsoft\NET Framework Setup\NDP\v1.1.4322" "Install"
  ;StrCmp $0 "1" +1 +3
  ;StrCpy $0 "1.1.4322"
  ;Goto end
  
  ;StrCpy $0 "none"

  end:
  Pop $2
  Exch $1
  Exch 1
  Exch $0
FunctionEnd


; latest version: http://nsis.sourceforge.net/Get_Windows_version
;--------------------------------
; GetWindowsVersion
;
; Based on Yazno's function, http://yazno.tripod.com/powerpimpit/
; Updated by Joost Verburg
;
; Returns on top of stack
;
; Windows Version (95, 98, ME, NT x.x, 2000, XP, 2003)
; or
; '' (Unknown Windows Version)
;
; Usage:
;   Call GetWindowsVersion
;   Pop $R0
;   ; at this point $R0 is "NT 4.0" or whatnot

Function GetWindowsVersion

  Push $R0
  Push $R1

  ClearErrors

  ReadRegStr $R0 HKLM "SOFTWARE\Microsoft\Windows NT\CurrentVersion" CurrentVersion

  IfErrors 0 lbl_winnt

   ; we are not NT
  ReadRegStr $R0 HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion" VersionNumber

  StrCpy $R1 $R0 1
  StrCmp $R1 '4' 0 lbl_error

  StrCpy $R1 $R0 3

  StrCmp $R1 '4.0' lbl_win32_95
  StrCmp $R1 '4.9' lbl_win32_ME lbl_win32_98

  lbl_win32_95:
    StrCpy $R0 '95'
  Goto lbl_done

  lbl_win32_98:
    StrCpy $R0 '98'
  Goto lbl_done

  lbl_win32_ME:
    StrCpy $R0 'ME'
  Goto lbl_done

  lbl_winnt:

  StrCpy $R1 $R0 1

  StrCmp $R1 '3' lbl_winnt_x
  StrCmp $R1 '4' lbl_winnt_x

  StrCpy $R1 $R0 3

  StrCmp $R1 '5.0' lbl_winnt_2000
  StrCmp $R1 '5.1' lbl_winnt_XP
  StrCmp $R1 '5.2' lbl_winnt_2003
  StrCmp $R1 '6.0' lbl_winnt_2008
  StrCmp $R1 '6.1' lbl_winnt_7
  StrCmp $R1 '6.2' lbl_winnt_8
  StrCmp $R1 '6.3' lbl_winnt_8_1 lbl_error
  
  lbl_winnt_x:
    StrCpy $R0 "NT $R0" 6
  Goto lbl_done

  lbl_winnt_2000:
    Strcpy $R0 '2000'
  Goto lbl_done

  lbl_winnt_XP:
    Strcpy $R0 'XP'
  Goto lbl_done

  lbl_winnt_2003:
    Strcpy $R0 '2003'
  Goto lbl_done

  lbl_winnt_2008:
    Strcpy $R0 '2008'
  Goto lbl_done
  
  lbl_winnt_7:
    Strcpy $R0 'win7'
  Goto lbl_done

  lbl_winnt_8:
    Strcpy $R0 'Win8'
  Goto lbl_done
  
  lbl_winnt_8_1:
    Strcpy $R0 'Win8.1'
  Goto lbl_done
  
  lbl_error:
    Strcpy $R0 ''
  lbl_done:

  Pop $R1
  Exch $R0

FunctionEnd

;--------------------------------
; Parse the version number
; x.y.z            --> x*1000000 + y*10000 + z*100 + 99
; x.y.z BETA       --> x*1000000 + y*10000 + z*100 + 0
; x.y.z BETAa      --> x*1000000 + y*10000 + z*100 + a

Function GetVersionNr
;  $R5 : version string
;  $0  : version number
;  $1  : element string
;  $2  : character counter
;  $3  : multiplicator
;  $4  : temp character

  Exch $R5
  Push $0
  Push $1
  Push $2
  Push $3
  Push $4

  StrCpy $0 "0"
  StrCpy $1 ""
  StrCpy $2 "-1"
  StrCpy $3 "1000000"

  loop:
  IntOp $2 $2 + 1
  StrCpy $4 $R5 1 $2   ;Copy next character from version string
  StrCmp $4 "" dotFound
  StrCmp $4 " " dotFound
  StrCmp $4 "." dotFound
  StrCpy $1 $1$4       ;Add character to element string
  Goto loop

  dotFound:
  IntOp $1 $1 * $3     ;Multiply value with its weight
  IntOp $0 $0 + $1     ;Add weighted value to version nr
  IntOp $3 $3 / 100    ;Decrease weight of next value
  StrCpy $1 ""         ;Initialize element string
  StrCmp $4 "." loop

  ${StrLoc} $2 $R5 "BETA" "<"
  ${If} $2 != ""
    ;Get BETA number
    ${If} $2 > 0
      IntOp $2 $2 * -1
      StrCpy $1 $R5 10 $2  ;Copy BETA number to $1
      IntOp $0 $0 + $1  ;Add BETA number to version number
    ${EndIf}
  ${Else}
    IntOp $0 $0 + 99  ;Add 99 to version number if it is not a BETA version
  ${EndIf}

  Pop $4
  Pop $3
  Pop $2
  Pop $1
  StrCpy $R5 $0
  Pop $0
  Exch $R5

FunctionEnd


;--------------------------------
; Service account page

Function ServiceAccountPage
  ;Check if install as service is selected
  ${Unless} ${SectionIsSelected} ${DATCOOR_SERVICE}
    Abort
  ${EndUnless}
  !insertmacro MUI_HEADER_TEXT "$(TEXT_SERVICEACCOUNT_TITLE)" "$(TEXT_SERVICEACCOUNT_SUBTITLE)"
  ${If} $ServiceUserName == ""
    !insertmacro MUI_INSTALLOPTIONS_WRITE "ServiceAccount.ini" "Field 2" "State" "1"
    !insertmacro MUI_INSTALLOPTIONS_WRITE "ServiceAccount.ini" "Field 3" "State" "0"
  ${Else}
    !insertmacro MUI_INSTALLOPTIONS_WRITE "ServiceAccount.ini" "Field 2" "State" "0"
    !insertmacro MUI_INSTALLOPTIONS_WRITE "ServiceAccount.ini" "Field 3" "State" "1"
  ${EndIf}
  !insertmacro MUI_INSTALLOPTIONS_WRITE "ServiceAccount.ini" "Field 5" "State" $ServiceUserName
  !insertmacro MUI_INSTALLOPTIONS_WRITE "ServiceAccount.ini" "Field 7" "State" $ServicePassword
  !insertmacro MUI_INSTALLOPTIONS_DISPLAY "ServiceAccount.ini"

FunctionEnd


;--------------------------------
; String resources

LangString TEXT_SERVICEACCOUNT_TITLE      ${LANG_ENGLISH} "Select user account"
LangString TEXT_SERVICEACCOUNT_SUBTITLE   ${LANG_ENGLISH} "Select the user account the ibaDatCoordinator service should use."
LangString DESC_DATCOOR_NOSERVICE         ${LANG_ENGLISH} "ibaDatCoordinator"
LangString DESC_DATCOOR_SERVICE           ${LANG_ENGLISH} "ibaDatCoordinator Server/Client"
LangString DESC_DATCOOR_CLIENT           ${LANG_ENGLISH} "ibaDatCoordinator Client"
LangString TEXT_OS_NOT_SUPPORTED          ${LANG_ENGLISH} "This operating system is not supported."
LangString TEXT_NOT_ADMINISTRATOR         ${LANG_ENGLISH} "You do not have sufficient privileges to complete this installation for all users of the machine.  Log on as an administrator and then retry this installation."
LangString TEXT_FRAMEWORK_MISSING         ${LANG_ENGLISH} "The .NET framework version 4.5.2 is not installed. Please install this before running the ibaPDA installer. The .NET framework can be found on the $\"iba Software & Manuals$\" DVD or it can be downloaded via windows update."
LangString TEXT_UNINSTALL                 ${LANG_ENGLISH} "Uninstall ${PRODUCT_NAME}"
LangString TEXT_ALREADY_INSTALLED         ${LANG_ENGLISH} "${PRODUCT_NAME} v${PRODUCT_VERSION} is already installed. Do you wish to reinstall?"
LangString TEXT_OLDER_INSTALLED           ${LANG_ENGLISH} "An older version of ${PRODUCT_NAME} is installed. Do you wish to upgrade to version ${PRODUCT_VERSION}?"
LangString TEXT_NEWER_INSTALLED           ${LANG_ENGLISH} "A newer version of ${PRODUCT_NAME} is installed."
LangString TEXT_PREV_UNINSTALLING         ${LANG_ENGLISH} "Removing older version of ${PRODUCT_NAME}"
LangString TEXT_STILL_RUNNING             ${LANG_ENGLISH} "Cannot delete the application you are trying to remove. Perhaps it is still running. If so, please close it and try again."
LangString DESC_REMAINING                 ${LANG_ENGLISH} " (%d %s%s remaining)"
LangString DESC_PROGRESS                  ${LANG_ENGLISH} "%dkB (%d%%) of %dkB @ %d.%01dkB/s" ;"%d.%01dkB/s" ;"%dkB (%d%%) of %dkB @ %d.%01dkB/s"
LangString DESC_PLURAL                    ${LANG_ENGLISH} "s"
LangString DESC_HOUR                      ${LANG_ENGLISH} "hour"
LangString DESC_MINUTE                    ${LANG_ENGLISH} "minute"
LangString DESC_SECOND                    ${LANG_ENGLISH} "second"
LangString DESC_CONNECTING                ${LANG_ENGLISH} "Connecting..."
LangString DESC_DOWNLOADING               ${LANG_ENGLISH} "Downloading %s"
LangString DESC_INSTALLING                ${LANG_ENGLISH} "Installing"
LangString TEXT_SERVICE_INSTALL           ${LANG_ENGLISH} "Installing service"
LangString TEXT_SERVICE_STOP              ${LANG_ENGLISH} "Stopping service"
LangString TEXT_SERVICE_REMOVE            ${LANG_ENGLISH} "Deleting service"
LangString TEXT_SERVICEORSTANDALONE_TITLE ${LANG_ENGLISH} "Choose Installation Type"
LangString TEXT_SERVICEORSTANDALONE_SUBTITLE ${LANG_ENGLISH} "Choose ibaDatCoordinator installation type"
LangString TEXT_INSTALLSERVICE            ${LANG_ENGLISH} "Install ibaDatCoordinator server and client"
LangString TEXT_INSTALLSTANDALONE         ${LANG_ENGLISH} "Install ibaDatCoordinator as stand alone executable"
LangString TEXT_INSTALLCLIENT         ${LANG_ENGLISH} "Install ibaDatCoordinator client only"
LangString TEXT_LOG_FILES                 ${LANG_ENGLISH} "log files"
LangString TEXT_IBAFILES_INSTALL          ${LANG_ENGLISH} "Installing ibaFiles"
LangString TEXT_CLOSE_STATUS              ${LANG_ENGLISH} "ibaPDA server status is running. Please close the ibaPDA server status program before continuing the installation."
LangString TEXT_STATUS_STOP               ${LANG_ENGLISH} "Stopping ibaDatCoordinator server status"

LangString TEXT_SERVICEACCOUNT_TITLE      ${LANG_GERMAN}  "Benutzerkonto wählen"
LangString TEXT_SERVICEACCOUNT_SUBTITLE   ${LANG_GERMAN}  "Wählen Sie das Benutzerkonto für den Server-Dienst aus."
LangString DESC_DATCOOR_NOSERVICE         ${LANG_GERMAN} "ibaDatCoordinator"
LangString DESC_DATCOOR_SERVICE           ${LANG_GERMAN} "ibaDatCoordinator Server/Client"
LangString DESC_DATCOOR_CLIENT           ${LANG_GERMAN} "ibaDatCoordinator Client"
LangString TEXT_OS_NOT_SUPPORTED          ${LANG_GERMAN} "Das Betriebssystem ist nicht unterstützt."
LangString TEXT_NOT_ADMINISTRATOR         ${LANG_GERMAN} "Sie besitzen keine ausreichenden Berechtigungen, um diese Installation für alle Benutzer dieses Computers auszuführen. Melden Sie sich als Administrator an, und wiederholen Sie diese Installation."
LangString TEXT_FRAMEWORK_MISSING         ${LANG_GERMAN}  "Das .NET Framework, Version 4.5.2, ist nicht installiert. Bitte installieren Sie dies zunächst, bevor Sie mit der Installation von ibaPDA beginnen. Das .NET Framework finden Sie auf der DVD $\"iba Software & Manuals$\" oder als Download via Windows-Update."
LangString TEXT_UNINSTALL                 ${LANG_GERMAN} "${PRODUCT_NAME} deinstallieren"
LangString TEXT_ALREADY_INSTALLED         ${LANG_GERMAN} "${PRODUCT_NAME} v${PRODUCT_VERSION} ist bereits installiert. Wollen Sie die Neuinstallation trotzdem durchführen?"
LangString TEXT_OLDER_INSTALLED           ${LANG_GERMAN} "Eine ältere Version von ${PRODUCT_NAME} ist bereits installiert. Wollen Sie ein upgrade auf die neuere Version ${PRODUCT_VERSION} durchführen?"
LangString TEXT_NEWER_INSTALLED           ${LANG_GERMAN} "Eine neuere Version von ${PRODUCT_NAME} ist bereits installiert."
LangString TEXT_PREV_UNINSTALLING         ${LANG_GERMAN} "Ältere Version von ${PRODUCT_NAME} wird entfernt..."
LangString TEXT_STILL_RUNNING             ${LANG_GERMAN} "Die Anwendung, die Sie entfernen wollen kann nicht gelöscht werden. Eventuell wird sie noch ausgeführt. Wenn dem so ist, beenden Sie bitte die Anwendung und versuchen Sie es erneut."
LangString DESC_REMAINING                 ${LANG_GERMAN} " (%d %s%s)"
LangString DESC_PROGRESS                  ${LANG_GERMAN} "%dkB (%d%%) of %dkB @ %d.%01dkB/s" ;"%d.%01dkB/s" ;"%dkB (%d%%) of %dkB @ %d.%01dkB/s"
LangString DESC_PLURAL                    ${LANG_GERMAN} "n"
LangString DESC_HOUR                      ${LANG_GERMAN} "Stunde"
LangString DESC_MINUTE                    ${LANG_GERMAN} "Minute"
LangString DESC_SECOND                    ${LANG_GERMAN} "Sekunde"
LangString DESC_CONNECTING                ${LANG_GERMAN} "Verbinden..."
LangString DESC_DOWNLOADING               ${LANG_GERMAN} "%s wird heruntergeladen"
LangString DESC_INSTALLING                ${LANG_GERMAN} "wird installiert"
LangString TEXT_SERVICE_INSTALL           ${LANG_GERMAN} "Dienst wird installiert"
LangString TEXT_SERVICE_STOP              ${LANG_GERMAN} "Dienst wird angehalten"
LangString TEXT_SERVICE_REMOVE            ${LANG_GERMAN} "Dienst wird gelöscht"
LangString TEXT_SERVICEORSTANDALONE_TITLE ${LANG_GERMAN} "Installationsart auswählen"
LangString TEXT_SERVICEORSTANDALONE_SUBTITLE ${LANG_GERMAN} "Wählen Sie die Installationsart für ibaDatCoordinator aus"
LangString TEXT_INSTALLSERVICE            ${LANG_GERMAN} "ibaDatCoordinator Server und Client installieren"
LangString TEXT_INSTALLSTANDALONE         ${LANG_GERMAN} "ibaDatCoordinator nur als Programm installieren"
LangString TEXT_INSTALLCLIENT         	  ${LANG_GERMAN} "Nur ibaDatCoordinator Client installieren"
LangString TEXT_LOG_FILES                 ${LANG_GERMAN} "Log Dateien"
LangString TEXT_IBAFILES_INSTALL          ${LANG_GERMAN}  "ibaFiles wird installiert"
LangString TEXT_CLOSE_STATUS              ${LANG_GERMAN}  "ibaDatCoordinator Server Status läuft. Bitte schließen Sie das ibaDatCoordinator Server Status-Programm, bevor Sie mit der Installation fortfahren."
LangString TEXT_STATUS_STOP               ${LANG_GERMAN}  "ibaDatCoordinator Server Status wird angehalten"

LangString TEXT_SERVICEACCOUNT_TITLE      ${LANG_FRENCH}  "Choisir le compte d'utilisateur"
LangString TEXT_SERVICEACCOUNT_SUBTITLE   ${LANG_FRENCH}  "Choisir le compte d'utilisateur employé par le service de serveur."
LangString DESC_DATCOOR_NOSERVICE         ${LANG_FRENCH} "ibaDatCoordinator"
LangString DESC_DATCOOR_SERVICE           ${LANG_FRENCH} "ibaDatCoordinator Serveur/Client"
LangString DESC_DATCOOR_CLIENT           ${LANG_FRENCH} "ibaDatCoordinator Client"
LangString TEXT_OS_NOT_SUPPORTED          ${LANG_FRENCH} "Le système d'exploitation n'est pas support?"
LangString TEXT_NOT_ADMINISTRATOR         ${LANG_FRENCH} "Vous n'avez pas assez de privilèges pour effectuer cette installation pour tous les utilisateurs de cet ordinateur. Connectez-vous en tant qu'administrateur et réessayez cette installation."
LangString TEXT_FRAMEWORK_MISSING         ${LANG_FRENCH}  "Le .NET framework version 4.5.2 n'est pas installée. Veuillez installer ceci avant d' excecuter l'installateur d'ibaPDA. Le .NET framework peut être trouvé sur le DVD $\"iba Software & Manuals$\" ou il peut être téléchargé par l'intermédiaire de Windows Update."
LangString TEXT_UNINSTALL                 ${LANG_FRENCH} "Désinstaller ${PRODUCT_NAME}"
LangString TEXT_ALREADY_INSTALLED         ${LANG_FRENCH} "${PRODUCT_NAME} v${PRODUCT_VERSION} est déj?install? Souhaitez-vous procéder ?une réinstallation?"
LangString TEXT_OLDER_INSTALLED           ${LANG_FRENCH} "Une ancienne version de ${PRODUCT_NAME} est déj?installée. Souhaitez-vous une mise ?niveau ?la nouvelle version ${PRODUCT_VERSION}?"
LangString TEXT_NEWER_INSTALLED           ${LANG_FRENCH} "Une version plus récente de ${PRODUCT_NAME} est déj?installée."
LangString TEXT_PREV_UNINSTALLING         ${LANG_FRENCH} "Suppression de l'ancienne version de ${PRODUCT_NAME}."
LangString TEXT_STILL_RUNNING             ${LANG_FRENCH} "L'application que vous voulez supprimer ne peut pas être effacée. Elle est éventuellement en cours d'exécution. Dans ce cas, fermez l'application et réessayez."
LangString DESC_REMAINING                 ${LANG_FRENCH} " (%d %s%s restant)"
LangString DESC_PROGRESS                  ${LANG_FRENCH} "%dkB (%d%%) of %dkB @ %d.%01dkB/s" ;"%d.%01dkB/s" ;"%dkB (%d%%) of %dkB @ %d.%01dkB/s"
LangString DESC_PLURAL                    ${LANG_FRENCH} "s"
LangString DESC_HOUR                      ${LANG_FRENCH} "Heure"
LangString DESC_MINUTE                    ${LANG_FRENCH} "Minute"
LangString DESC_SECOND                    ${LANG_FRENCH} "Seconde"
LangString DESC_CONNECTING                ${LANG_FRENCH} "Connexion..."
LangString DESC_DOWNLOADING               ${LANG_FRENCH} "Téléchargement de %s"
LangString DESC_INSTALLING                ${LANG_FRENCH} "Installation"
LangString TEXT_SERVICE_INSTALL           ${LANG_FRENCH} "Installation du service"
LangString TEXT_SERVICE_STOP              ${LANG_FRENCH} "Arrêt du service"
LangString TEXT_SERVICE_REMOVE            ${LANG_FRENCH} "Suppression du service"
LangString TEXT_SERVICEORSTANDALONE_TITLE ${LANG_FRENCH} "Choisir Type d'Installation"
LangString TEXT_SERVICEORSTANDALONE_SUBTITLE ${LANG_FRENCH} "Choisir le type d'installation d'ibaDatCoordinator"
LangString TEXT_INSTALLSERVICE            ${LANG_FRENCH} "Installer  l'ibaDatCoordinator comme serveur et client"
LangString TEXT_INSTALLSTANDALONE         ${LANG_FRENCH} "Installer l'ibaDatCoordinator comme exécutable autonome"
LangString TEXT_INSTALLCLIENT          ${LANG_FRENCH} "Installer  l'ibaDatCoordinator comme client seulement"
LangString TEXT_LOG_FILES                 ${LANG_FRENCH} "fichiers log"
LangString TEXT_IBAFILES_INSTALL          ${LANG_FRENCH}  "Installation de ibaFiles"
LangString TEXT_CLOSE_STATUS              ${LANG_FRENCH}  "Le logiciel état de serveur ibaDatCoordinator est en cours d'exécution. Veuillez fermer le logiciel état de serveur ibaDatCoordinator avant de continuer
LangString TEXT_STATUS_STOP               ${LANG_FRENCH}  "Arrêt du logiciel état de serveur ibaDatCoordinator" l'installation."