; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "ibaDatCoordinator Roh Plugin"

!define PRODUCT_VERSION "2.4.0"
!define PRODUCT_FILE_VERSION "2.4.0.0"

!include "PluginInstaller.nsh"
 
Function CopyFiles
  ClearErrors
  DetailPrint "Copying plugin files"
  SetOutPath "$PluginPath"
  File "..\Dependencies\msvcr100.dll"
  File "..\Dependencies\msvcp100.dll"
  File "..\RohPlugin\bin\Release\Alunorf_roh_plugin.dll"
  File "..\RohPlugin\bin\Release\RohWriter.dll"
  IfErrors copyError copyOk
copyError:
  Push "error"
  Return
copyOk:
  Push "success"
FunctionEnd