; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "ibaDatCoordinator Roh Plugin Installer"
!define PRODUCT_SHORTNAME "Roh"
!define PRODUCT_VERSION "2.1.3"
!define PRODUCT_FILE_VERSION "2.1.3.0"
!define PRODUCT_PUBLISHER "iba AG"
!define PRODUCT_WEB_SITE "http://www.iba-ag.com"

!include "PluginInstaller.nsh"
 
Function CopyFiles
  ClearErrors
  DetailPrint "Copying plugin files"
  SetOutPath "$PluginPath"
  File "..\Dependencies\msvcr100.dll"
  File "..\Dependencies\msvcp100.dll"
  File "..\RohPlugin\bin\Release\Alunorf_roh_plugin.dll"
  File "..\RohPlugin\bin\Release\RohWriter.dll"
  IfErrors copyError copyOk
copyError:
  Push "error"
  Return
copyOk:
  Push "success"
FunctionEnd