; Script generated by the HM NIS Edit Script Wizard.
; HM NIS Edit Wizard helper defines

!define PRODUCT_NAME "ibaDatCoordinator Roh Plugin"

!ifndef PRODUCT_VERSION
  !define PRODUCT_VERSION "3.0.0"
  !define PRODUCT_FILE_VERSION "3.0.0.0"
!endif

!include "PluginInstaller.nsh"
 
Function CopyFiles
  ClearErrors
  DetailPrint "Copying plugin files"
  SetOutPath "$PluginPath"
  File "..\Dependencies\msvcr100.dll"
  File "..\Dependencies\msvcp100.dll"
  File "..\RohPlugin\bin\Release\Alunorf_roh_plugin.dll"
  File "..\RohPlugin\bin\Release\RohWriter.dll"
  IfErrors copyError copyOk
copyError:
  Push "error"
  Return
copyOk:
  Push "success"
FunctionEnd