; Script generated by the HM NIS Edit Script Wizard.
; HM NIS Edit Wizard helper defines

!define PRODUCT_NAME "ibaDatCoordinator S7 Writer Plugin"

!ifndef PRODUCT_VERSION
  !define PRODUCT_VERSION "3.0.0"
  !define PRODUCT_FILE_VERSION "3.0.0.0"
!endif

!include "PluginInstaller.nsh"
 
Function CopyFiles
  ClearErrors
  DetailPrint "Copying plugin files"

  SetOutPath "$ibaDatCoordinatorPath"
  File "..\S7-writer\AGLink\AGLink40.dll"

  SetOutPath "$PluginPath"
  File "..\S7-writer-plugin\bin\Release\S7-writer.dll"
  File "..\S7-writer-plugin\bin\Release\S7-writer-plugin.dll"

  IfErrors copyError copyOk
copyError:
  Push "error"
  Return
copyOk:
  Push "success"
FunctionEnd