; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "ibaDatCoordinator S7 Writer Plugin Installer"
!define PRODUCT_SHORTNAME "S7-Writer"
!define PRODUCT_VERSION "2.0.0"
!define PRODUCT_FILE_VERSION "2.0.0.0"
!define PRODUCT_PUBLISHER "iba AG"
!define PRODUCT_WEB_SITE "http://www.iba-ag.com"

!include "PluginInstaller.nsh"
 
Function CopyFiles
  ClearErrors
  DetailPrint "Copying plugin files"
  SetOutPath "$PluginPath"
  File "..\S7-writer-plugin\bin\Release\S7-writer.dll"
  File "..\S7-writer-plugin\bin\Release\S7-writer-plugin.dll"
  File "..\S7-writer\AGLink\AGLink40.dll"
  IfErrors copyError copyOk
copyError:
  Push "error"
  Return
copyOk:
  Push "success"
FunctionEnd