; Script generated by the HM NIS Edit Script Wizard.
; HM NIS Edit Wizard helper defines

!define PRODUCT_NAME "ibaDatCoordinator TKS Xml Plugin"

!ifndef PRODUCT_VERSION
  !define PRODUCT_VERSION "3.0.0"
  !define PRODUCT_FILE_VERSION "3.0.0.0"
!endif

!define DATCO_MIN 3000000
!define DATCO_MIN_STR "3.0.0"

!include "PluginInstaller.nsh"

Function CopyFiles
  ClearErrors
  DetailPrint "Copying plugin files"
  SetOutPath "$PluginPath"
  File "..\TKS-XML-plugin\bin\Release\TKS-XML-plugin.dll"
  IfErrors copyError copyOk
copyError:
  Push "error"
  Return
copyOk:
  Push "success"
FunctionEnd
